-- Create "changes" table
CREATE TABLE `changes` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `branch` text NOT NULL, `name` text NOT NULL, `status` text NOT NULL DEFAULT ('active'), `project_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `changes_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `status_valid` CHECK (status IN ('active','closed')));
-- Create index "change_project_id_branch" to table: "changes"
CREATE UNIQUE INDEX `change_project_id_branch` ON `changes` (`project_id`, `branch`);
-- Create index "change_project_id_name" to table: "changes"
CREATE UNIQUE INDEX `change_project_id_name` ON `changes` (`project_id`, `name`);
-- Create "content_objects" table
CREATE TABLE `content_objects` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `hash` text NOT NULL, `size_bytes` integer NOT NULL, `bytes` blob NOT NULL, `project_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `content_objects_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION);
-- Create index "contentobject_project_id_hash" to table: "content_objects"
CREATE UNIQUE INDEX `contentobject_project_id_hash` ON `content_objects` (`project_id`, `hash`);
-- Create "events" table
CREATE TABLE `events` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `position` integer NOT NULL, `type` text NOT NULL, `payload` text NOT NULL, `occurred_at` text NOT NULL, `agent_kind` text NULL, `agent_name` text NULL, `session_id` text NULL, `idempotency_hash` text NOT NULL, `project_id` text NOT NULL, `change_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `events_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `events_changes_change` FOREIGN KEY (`change_id`) REFERENCES `changes` (`id`) ON DELETE NO ACTION, CONSTRAINT `agent_kind_valid` CHECK (agent_kind IN ('phase','orchestrator','subagent')));
-- Create index "event_change_id_position" to table: "events"
CREATE UNIQUE INDEX `event_change_id_position` ON `events` (`change_id`, `position`);
-- Create index "event_idempotency_hash" to table: "events"
CREATE UNIQUE INDEX `event_idempotency_hash` ON `events` (`idempotency_hash`);
-- Create "event_record_pins" table
CREATE TABLE `event_record_pins` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `project_id` text NOT NULL, `event_id` text NOT NULL, `record_version_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `event_record_pins_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `event_record_pins_events_event` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE NO ACTION, CONSTRAINT `event_record_pins_record_versions_record_version` FOREIGN KEY (`record_version_id`) REFERENCES `record_versions` (`id`) ON DELETE NO ACTION);
-- Create index "eventrecordpin_event_id_record_version_id" to table: "event_record_pins"
CREATE UNIQUE INDEX `eventrecordpin_event_id_record_version_id` ON `event_record_pins` (`event_id`, `record_version_id`);
-- Create "iteration_notes" table
CREATE TABLE `iteration_notes` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `file_path` text NULL, `line_from` integer NULL, `line_to` integer NULL, `body` text NOT NULL, `status` text NOT NULL DEFAULT ('pending'), `delivered_at` text NULL, `resolved_at` text NULL, `project_id` text NOT NULL, `change_id` text NOT NULL, `event_id` text NULL, PRIMARY KEY (`id`), CONSTRAINT `iteration_notes_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `iteration_notes_changes_change` FOREIGN KEY (`change_id`) REFERENCES `changes` (`id`) ON DELETE NO ACTION, CONSTRAINT `iteration_notes_events_event` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE SET NULL, CONSTRAINT `file_anchor` CHECK (file_path IS NULL OR event_id IS NOT NULL), CONSTRAINT `range_anchor` CHECK ((line_from IS NULL AND line_to IS NULL) OR (file_path IS NOT NULL AND line_from <= line_to)), CONSTRAINT `status_valid` CHECK (status IN ('pending','delivered','resolved')));
-- Create "projects" table
CREATE TABLE `projects` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `name` text NOT NULL, `status` text NOT NULL DEFAULT ('active'), PRIMARY KEY (`id`), CONSTRAINT `status_valid` CHECK (status IN ('active','inactive')));
-- Create "project_paths" table
CREATE TABLE `project_paths` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `machine_id` text NOT NULL, `root_path` text NOT NULL, `status` text NOT NULL DEFAULT ('active'), `last_seen_at` text NOT NULL, `project_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `project_paths_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `status_valid` CHECK (status IN ('active','stale')));
-- Create index "projectpath_machine_id_root_path" to table: "project_paths"
CREATE UNIQUE INDEX `projectpath_machine_id_root_path` ON `project_paths` (`machine_id`, `root_path`);
-- Create "records" table
CREATE TABLE `records` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `owning_root` text NOT NULL, `slug` text NOT NULL, `project_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `records_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION);
-- Create index "record_project_id_owning_root_slug" to table: "records"
CREATE UNIQUE INDEX `record_project_id_owning_root_slug` ON `records` (`project_id`, `owning_root`, `slug`);
-- Create "record_branch_state" table
CREATE TABLE `record_branch_state` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `branch` text NOT NULL, `status` text NOT NULL, `malformed` integer NOT NULL DEFAULT (0), `project_id` text NOT NULL, `record_id` text NOT NULL, `current_version_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `record_branch_state_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `record_branch_state_records_record` FOREIGN KEY (`record_id`) REFERENCES `records` (`id`) ON DELETE NO ACTION, CONSTRAINT `record_branch_state_record_versions_current_version` FOREIGN KEY (`current_version_id`) REFERENCES `record_versions` (`id`) ON DELETE NO ACTION, CONSTRAINT `status_valid` CHECK (status IN ('active','deleted')));
-- Create index "recordbranchstate_record_id_branch" to table: "record_branch_state"
CREATE UNIQUE INDEX `recordbranchstate_record_id_branch` ON `record_branch_state` (`record_id`, `branch`);
-- Create "record_versions" table
CREATE TABLE `record_versions` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `status` text NOT NULL, `kind` text NULL, `doc_status` text NULL, `frozen_at` text NULL, `project_id` text NOT NULL, `record_id` text NOT NULL, `content_object_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `record_versions_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `record_versions_records_record` FOREIGN KEY (`record_id`) REFERENCES `records` (`id`) ON DELETE NO ACTION, CONSTRAINT `record_versions_content_objects_content_object` FOREIGN KEY (`content_object_id`) REFERENCES `content_objects` (`id`) ON DELETE NO ACTION, CONSTRAINT `status_valid` CHECK (status IN ('current','frozen')));
-- Create "record_version_refs" table
CREATE TABLE `record_version_refs` (`id` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `relation` text NOT NULL, `target_slug` text NOT NULL, `target_owning_root` text NULL, `dangling` integer NOT NULL DEFAULT (0), `project_id` text NOT NULL, `record_version_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `record_version_refs_projects_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE NO ACTION, CONSTRAINT `record_version_refs_record_versions_record_version` FOREIGN KEY (`record_version_id`) REFERENCES `record_versions` (`id`) ON DELETE NO ACTION);
