// Code generated by ent, DO NOT EDIT.

package recordversionref

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the recordversionref type in the database.
	Label = "record_version_ref"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldRecordVersionID holds the string denoting the record_version_id field in the database.
	FieldRecordVersionID = "record_version_id"
	// FieldRelation holds the string denoting the relation field in the database.
	FieldRelation = "relation"
	// FieldTargetSlug holds the string denoting the target_slug field in the database.
	FieldTargetSlug = "target_slug"
	// FieldTargetOwningRoot holds the string denoting the target_owning_root field in the database.
	FieldTargetOwningRoot = "target_owning_root"
	// FieldDangling holds the string denoting the dangling field in the database.
	FieldDangling = "dangling"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeRecordVersion holds the string denoting the record_version edge name in mutations.
	EdgeRecordVersion = "record_version"
	// Table holds the table name of the recordversionref in the database.
	Table = "record_version_refs"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "record_version_refs"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// RecordVersionTable is the table that holds the record_version relation/edge.
	RecordVersionTable = "record_version_refs"
	// RecordVersionInverseTable is the table name for the RecordVersion entity.
	// It exists in this package in order to avoid circular dependency with the "recordversion" package.
	RecordVersionInverseTable = "record_versions"
	// RecordVersionColumn is the table column denoting the record_version relation/edge.
	RecordVersionColumn = "record_version_id"
)

// Columns holds all SQL columns for recordversionref fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProjectID,
	FieldRecordVersionID,
	FieldRelation,
	FieldTargetSlug,
	FieldTargetOwningRoot,
	FieldDangling,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/franwerner/matecito-ai/apps/api/internal/store/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() string
	// DefaultDangling holds the default value on creation for the "dangling" field.
	DefaultDangling int8
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the RecordVersionRef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByRecordVersionID orders the results by the record_version_id field.
func ByRecordVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordVersionID, opts...).ToFunc()
}

// ByRelation orders the results by the relation field.
func ByRelation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelation, opts...).ToFunc()
}

// ByTargetSlug orders the results by the target_slug field.
func ByTargetSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetSlug, opts...).ToFunc()
}

// ByTargetOwningRoot orders the results by the target_owning_root field.
func ByTargetOwningRoot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetOwningRoot, opts...).ToFunc()
}

// ByDangling orders the results by the dangling field.
func ByDangling(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDangling, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByRecordVersionField orders the results by record_version field.
func ByRecordVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordVersionStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
	)
}
func newRecordVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RecordVersionTable, RecordVersionColumn),
	)
}
