// Code generated by ent, DO NOT EDIT.

package recordversion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldProjectID, v))
}

// RecordID applies equality check predicate on the "record_id" field. It's identical to RecordIDEQ.
func RecordID(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldRecordID, v))
}

// ContentObjectID applies equality check predicate on the "content_object_id" field. It's identical to ContentObjectIDEQ.
func ContentObjectID(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldContentObjectID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldStatus, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldKind, v))
}

// DocStatus applies equality check predicate on the "doc_status" field. It's identical to DocStatusEQ.
func DocStatus(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldDocStatus, v))
}

// FrozenAt applies equality check predicate on the "frozen_at" field. It's identical to FrozenAtEQ.
func FrozenAt(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldFrozenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtContains applies the Contains predicate on the "updated_at" field.
func UpdatedAtContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldUpdatedAt, v))
}

// UpdatedAtHasPrefix applies the HasPrefix predicate on the "updated_at" field.
func UpdatedAtHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldUpdatedAt, v))
}

// UpdatedAtHasSuffix applies the HasSuffix predicate on the "updated_at" field.
func UpdatedAtHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldUpdatedAt, v))
}

// UpdatedAtEqualFold applies the EqualFold predicate on the "updated_at" field.
func UpdatedAtEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldUpdatedAt, v))
}

// UpdatedAtContainsFold applies the ContainsFold predicate on the "updated_at" field.
func UpdatedAtContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldProjectID, v))
}

// RecordIDEQ applies the EQ predicate on the "record_id" field.
func RecordIDEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldRecordID, v))
}

// RecordIDNEQ applies the NEQ predicate on the "record_id" field.
func RecordIDNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldRecordID, v))
}

// RecordIDIn applies the In predicate on the "record_id" field.
func RecordIDIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldRecordID, vs...))
}

// RecordIDNotIn applies the NotIn predicate on the "record_id" field.
func RecordIDNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldRecordID, vs...))
}

// RecordIDGT applies the GT predicate on the "record_id" field.
func RecordIDGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldRecordID, v))
}

// RecordIDGTE applies the GTE predicate on the "record_id" field.
func RecordIDGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldRecordID, v))
}

// RecordIDLT applies the LT predicate on the "record_id" field.
func RecordIDLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldRecordID, v))
}

// RecordIDLTE applies the LTE predicate on the "record_id" field.
func RecordIDLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldRecordID, v))
}

// RecordIDContains applies the Contains predicate on the "record_id" field.
func RecordIDContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldRecordID, v))
}

// RecordIDHasPrefix applies the HasPrefix predicate on the "record_id" field.
func RecordIDHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldRecordID, v))
}

// RecordIDHasSuffix applies the HasSuffix predicate on the "record_id" field.
func RecordIDHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldRecordID, v))
}

// RecordIDEqualFold applies the EqualFold predicate on the "record_id" field.
func RecordIDEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldRecordID, v))
}

// RecordIDContainsFold applies the ContainsFold predicate on the "record_id" field.
func RecordIDContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldRecordID, v))
}

// ContentObjectIDEQ applies the EQ predicate on the "content_object_id" field.
func ContentObjectIDEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldContentObjectID, v))
}

// ContentObjectIDNEQ applies the NEQ predicate on the "content_object_id" field.
func ContentObjectIDNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldContentObjectID, v))
}

// ContentObjectIDIn applies the In predicate on the "content_object_id" field.
func ContentObjectIDIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldContentObjectID, vs...))
}

// ContentObjectIDNotIn applies the NotIn predicate on the "content_object_id" field.
func ContentObjectIDNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldContentObjectID, vs...))
}

// ContentObjectIDGT applies the GT predicate on the "content_object_id" field.
func ContentObjectIDGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldContentObjectID, v))
}

// ContentObjectIDGTE applies the GTE predicate on the "content_object_id" field.
func ContentObjectIDGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldContentObjectID, v))
}

// ContentObjectIDLT applies the LT predicate on the "content_object_id" field.
func ContentObjectIDLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldContentObjectID, v))
}

// ContentObjectIDLTE applies the LTE predicate on the "content_object_id" field.
func ContentObjectIDLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldContentObjectID, v))
}

// ContentObjectIDContains applies the Contains predicate on the "content_object_id" field.
func ContentObjectIDContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldContentObjectID, v))
}

// ContentObjectIDHasPrefix applies the HasPrefix predicate on the "content_object_id" field.
func ContentObjectIDHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldContentObjectID, v))
}

// ContentObjectIDHasSuffix applies the HasSuffix predicate on the "content_object_id" field.
func ContentObjectIDHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldContentObjectID, v))
}

// ContentObjectIDEqualFold applies the EqualFold predicate on the "content_object_id" field.
func ContentObjectIDEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldContentObjectID, v))
}

// ContentObjectIDContainsFold applies the ContainsFold predicate on the "content_object_id" field.
func ContentObjectIDContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldContentObjectID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldStatus, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldKind, v))
}

// KindIsNil applies the IsNil predicate on the "kind" field.
func KindIsNil() predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIsNull(FieldKind))
}

// KindNotNil applies the NotNil predicate on the "kind" field.
func KindNotNil() predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotNull(FieldKind))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldKind, v))
}

// DocStatusEQ applies the EQ predicate on the "doc_status" field.
func DocStatusEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldDocStatus, v))
}

// DocStatusNEQ applies the NEQ predicate on the "doc_status" field.
func DocStatusNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldDocStatus, v))
}

// DocStatusIn applies the In predicate on the "doc_status" field.
func DocStatusIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldDocStatus, vs...))
}

// DocStatusNotIn applies the NotIn predicate on the "doc_status" field.
func DocStatusNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldDocStatus, vs...))
}

// DocStatusGT applies the GT predicate on the "doc_status" field.
func DocStatusGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldDocStatus, v))
}

// DocStatusGTE applies the GTE predicate on the "doc_status" field.
func DocStatusGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldDocStatus, v))
}

// DocStatusLT applies the LT predicate on the "doc_status" field.
func DocStatusLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldDocStatus, v))
}

// DocStatusLTE applies the LTE predicate on the "doc_status" field.
func DocStatusLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldDocStatus, v))
}

// DocStatusContains applies the Contains predicate on the "doc_status" field.
func DocStatusContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldDocStatus, v))
}

// DocStatusHasPrefix applies the HasPrefix predicate on the "doc_status" field.
func DocStatusHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldDocStatus, v))
}

// DocStatusHasSuffix applies the HasSuffix predicate on the "doc_status" field.
func DocStatusHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldDocStatus, v))
}

// DocStatusIsNil applies the IsNil predicate on the "doc_status" field.
func DocStatusIsNil() predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIsNull(FieldDocStatus))
}

// DocStatusNotNil applies the NotNil predicate on the "doc_status" field.
func DocStatusNotNil() predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotNull(FieldDocStatus))
}

// DocStatusEqualFold applies the EqualFold predicate on the "doc_status" field.
func DocStatusEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldDocStatus, v))
}

// DocStatusContainsFold applies the ContainsFold predicate on the "doc_status" field.
func DocStatusContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldDocStatus, v))
}

// FrozenAtEQ applies the EQ predicate on the "frozen_at" field.
func FrozenAtEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEQ(FieldFrozenAt, v))
}

// FrozenAtNEQ applies the NEQ predicate on the "frozen_at" field.
func FrozenAtNEQ(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNEQ(FieldFrozenAt, v))
}

// FrozenAtIn applies the In predicate on the "frozen_at" field.
func FrozenAtIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIn(FieldFrozenAt, vs...))
}

// FrozenAtNotIn applies the NotIn predicate on the "frozen_at" field.
func FrozenAtNotIn(vs ...string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotIn(FieldFrozenAt, vs...))
}

// FrozenAtGT applies the GT predicate on the "frozen_at" field.
func FrozenAtGT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGT(FieldFrozenAt, v))
}

// FrozenAtGTE applies the GTE predicate on the "frozen_at" field.
func FrozenAtGTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldGTE(FieldFrozenAt, v))
}

// FrozenAtLT applies the LT predicate on the "frozen_at" field.
func FrozenAtLT(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLT(FieldFrozenAt, v))
}

// FrozenAtLTE applies the LTE predicate on the "frozen_at" field.
func FrozenAtLTE(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldLTE(FieldFrozenAt, v))
}

// FrozenAtContains applies the Contains predicate on the "frozen_at" field.
func FrozenAtContains(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContains(FieldFrozenAt, v))
}

// FrozenAtHasPrefix applies the HasPrefix predicate on the "frozen_at" field.
func FrozenAtHasPrefix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasPrefix(FieldFrozenAt, v))
}

// FrozenAtHasSuffix applies the HasSuffix predicate on the "frozen_at" field.
func FrozenAtHasSuffix(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldHasSuffix(FieldFrozenAt, v))
}

// FrozenAtIsNil applies the IsNil predicate on the "frozen_at" field.
func FrozenAtIsNil() predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldIsNull(FieldFrozenAt))
}

// FrozenAtNotNil applies the NotNil predicate on the "frozen_at" field.
func FrozenAtNotNil() predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldNotNull(FieldFrozenAt))
}

// FrozenAtEqualFold applies the EqualFold predicate on the "frozen_at" field.
func FrozenAtEqualFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldEqualFold(FieldFrozenAt, v))
}

// FrozenAtContainsFold applies the ContainsFold predicate on the "frozen_at" field.
func FrozenAtContainsFold(v string) predicate.RecordVersion {
	return predicate.RecordVersion(sql.FieldContainsFold(FieldFrozenAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.RecordVersion {
	return predicate.RecordVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.RecordVersion {
	return predicate.RecordVersion(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecord applies the HasEdge predicate on the "record" edge.
func HasRecord() predicate.RecordVersion {
	return predicate.RecordVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RecordTable, RecordColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordWith applies the HasEdge predicate on the "record" edge with a given conditions (other predicates).
func HasRecordWith(preds ...predicate.Record) predicate.RecordVersion {
	return predicate.RecordVersion(func(s *sql.Selector) {
		step := newRecordStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasContentObject applies the HasEdge predicate on the "content_object" edge.
func HasContentObject() predicate.RecordVersion {
	return predicate.RecordVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ContentObjectTable, ContentObjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentObjectWith applies the HasEdge predicate on the "content_object" edge with a given conditions (other predicates).
func HasContentObjectWith(preds ...predicate.ContentObject) predicate.RecordVersion {
	return predicate.RecordVersion(func(s *sql.Selector) {
		step := newContentObjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecordVersion) predicate.RecordVersion {
	return predicate.RecordVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecordVersion) predicate.RecordVersion {
	return predicate.RecordVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecordVersion) predicate.RecordVersion {
	return predicate.RecordVersion(sql.NotPredicates(p))
}
