// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
)

// ChangeUpdate is the builder for updating Change entities.
type ChangeUpdate struct {
	config
	hooks    []Hook
	mutation *ChangeMutation
}

// Where appends a list predicates to the ChangeUpdate builder.
func (_u *ChangeUpdate) Where(ps ...predicate.Change) *ChangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChangeUpdate) SetUpdatedAt(v string) *ChangeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ChangeUpdate) SetNillableUpdatedAt(v *string) *ChangeUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ChangeUpdate) SetProjectID(v string) *ChangeUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ChangeUpdate) SetNillableProjectID(v *string) *ChangeUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetBranch sets the "branch" field.
func (_u *ChangeUpdate) SetBranch(v string) *ChangeUpdate {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *ChangeUpdate) SetNillableBranch(v *string) *ChangeUpdate {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChangeUpdate) SetName(v string) *ChangeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChangeUpdate) SetNillableName(v *string) *ChangeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChangeUpdate) SetStatus(v string) *ChangeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChangeUpdate) SetNillableStatus(v *string) *ChangeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ChangeUpdate) SetProject(v *Project) *ChangeUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ChangeMutation object of the builder.
func (_u *ChangeUpdate) Mutation() *ChangeMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ChangeUpdate) ClearProject() *ChangeUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChangeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChangeUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Change.project"`)
	}
	return nil
}

func (_u *ChangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(change.Table, change.Columns, sqlgraph.NewFieldSpec(change.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(change.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(change.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(change.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(change.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   change.ProjectTable,
			Columns: []string{change.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   change.ProjectTable,
			Columns: []string{change.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{change.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChangeUpdateOne is the builder for updating a single Change entity.
type ChangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChangeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChangeUpdateOne) SetUpdatedAt(v string) *ChangeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ChangeUpdateOne) SetNillableUpdatedAt(v *string) *ChangeUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ChangeUpdateOne) SetProjectID(v string) *ChangeUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ChangeUpdateOne) SetNillableProjectID(v *string) *ChangeUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetBranch sets the "branch" field.
func (_u *ChangeUpdateOne) SetBranch(v string) *ChangeUpdateOne {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *ChangeUpdateOne) SetNillableBranch(v *string) *ChangeUpdateOne {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChangeUpdateOne) SetName(v string) *ChangeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChangeUpdateOne) SetNillableName(v *string) *ChangeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChangeUpdateOne) SetStatus(v string) *ChangeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChangeUpdateOne) SetNillableStatus(v *string) *ChangeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ChangeUpdateOne) SetProject(v *Project) *ChangeUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ChangeMutation object of the builder.
func (_u *ChangeUpdateOne) Mutation() *ChangeMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ChangeUpdateOne) ClearProject() *ChangeUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ChangeUpdate builder.
func (_u *ChangeUpdateOne) Where(ps ...predicate.Change) *ChangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChangeUpdateOne) Select(field string, fields ...string) *ChangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Change entity.
func (_u *ChangeUpdateOne) Save(ctx context.Context) (*Change, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChangeUpdateOne) SaveX(ctx context.Context) *Change {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChangeUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Change.project"`)
	}
	return nil
}

func (_u *ChangeUpdateOne) sqlSave(ctx context.Context) (_node *Change, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(change.Table, change.Columns, sqlgraph.NewFieldSpec(change.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Change.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, change.FieldID)
		for _, f := range fields {
			if !change.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != change.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(change.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(change.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(change.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(change.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   change.ProjectTable,
			Columns: []string{change.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   change.ProjectTable,
			Columns: []string{change.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Change{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{change.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
