// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/contentobject"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/event"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/eventrecordpin"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/iterationnote"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/projectpath"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/record"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordbranchstate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversionref"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Change is the client for interacting with the Change builders.
	Change *ChangeClient
	// ContentObject is the client for interacting with the ContentObject builders.
	ContentObject *ContentObjectClient
	// Event is the client for interacting with the Event builders.
	Event *EventClient
	// EventRecordPin is the client for interacting with the EventRecordPin builders.
	EventRecordPin *EventRecordPinClient
	// IterationNote is the client for interacting with the IterationNote builders.
	IterationNote *IterationNoteClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectPath is the client for interacting with the ProjectPath builders.
	ProjectPath *ProjectPathClient
	// Record is the client for interacting with the Record builders.
	Record *RecordClient
	// RecordBranchState is the client for interacting with the RecordBranchState builders.
	RecordBranchState *RecordBranchStateClient
	// RecordVersion is the client for interacting with the RecordVersion builders.
	RecordVersion *RecordVersionClient
	// RecordVersionRef is the client for interacting with the RecordVersionRef builders.
	RecordVersionRef *RecordVersionRefClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Change = NewChangeClient(c.config)
	c.ContentObject = NewContentObjectClient(c.config)
	c.Event = NewEventClient(c.config)
	c.EventRecordPin = NewEventRecordPinClient(c.config)
	c.IterationNote = NewIterationNoteClient(c.config)
	c.Project = NewProjectClient(c.config)
	c.ProjectPath = NewProjectPathClient(c.config)
	c.Record = NewRecordClient(c.config)
	c.RecordBranchState = NewRecordBranchStateClient(c.config)
	c.RecordVersion = NewRecordVersionClient(c.config)
	c.RecordVersionRef = NewRecordVersionRefClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Change:            NewChangeClient(cfg),
		ContentObject:     NewContentObjectClient(cfg),
		Event:             NewEventClient(cfg),
		EventRecordPin:    NewEventRecordPinClient(cfg),
		IterationNote:     NewIterationNoteClient(cfg),
		Project:           NewProjectClient(cfg),
		ProjectPath:       NewProjectPathClient(cfg),
		Record:            NewRecordClient(cfg),
		RecordBranchState: NewRecordBranchStateClient(cfg),
		RecordVersion:     NewRecordVersionClient(cfg),
		RecordVersionRef:  NewRecordVersionRefClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Change:            NewChangeClient(cfg),
		ContentObject:     NewContentObjectClient(cfg),
		Event:             NewEventClient(cfg),
		EventRecordPin:    NewEventRecordPinClient(cfg),
		IterationNote:     NewIterationNoteClient(cfg),
		Project:           NewProjectClient(cfg),
		ProjectPath:       NewProjectPathClient(cfg),
		Record:            NewRecordClient(cfg),
		RecordBranchState: NewRecordBranchStateClient(cfg),
		RecordVersion:     NewRecordVersionClient(cfg),
		RecordVersionRef:  NewRecordVersionRefClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Change.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Change, c.ContentObject, c.Event, c.EventRecordPin, c.IterationNote,
		c.Project, c.ProjectPath, c.Record, c.RecordBranchState, c.RecordVersion,
		c.RecordVersionRef,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Change, c.ContentObject, c.Event, c.EventRecordPin, c.IterationNote,
		c.Project, c.ProjectPath, c.Record, c.RecordBranchState, c.RecordVersion,
		c.RecordVersionRef,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChangeMutation:
		return c.Change.mutate(ctx, m)
	case *ContentObjectMutation:
		return c.ContentObject.mutate(ctx, m)
	case *EventMutation:
		return c.Event.mutate(ctx, m)
	case *EventRecordPinMutation:
		return c.EventRecordPin.mutate(ctx, m)
	case *IterationNoteMutation:
		return c.IterationNote.mutate(ctx, m)
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *ProjectPathMutation:
		return c.ProjectPath.mutate(ctx, m)
	case *RecordMutation:
		return c.Record.mutate(ctx, m)
	case *RecordBranchStateMutation:
		return c.RecordBranchState.mutate(ctx, m)
	case *RecordVersionMutation:
		return c.RecordVersion.mutate(ctx, m)
	case *RecordVersionRefMutation:
		return c.RecordVersionRef.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChangeClient is a client for the Change schema.
type ChangeClient struct {
	config
}

// NewChangeClient returns a client for the Change from the given config.
func NewChangeClient(c config) *ChangeClient {
	return &ChangeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `change.Hooks(f(g(h())))`.
func (c *ChangeClient) Use(hooks ...Hook) {
	c.hooks.Change = append(c.hooks.Change, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `change.Intercept(f(g(h())))`.
func (c *ChangeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Change = append(c.inters.Change, interceptors...)
}

// Create returns a builder for creating a Change entity.
func (c *ChangeClient) Create() *ChangeCreate {
	mutation := newChangeMutation(c.config, OpCreate)
	return &ChangeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Change entities.
func (c *ChangeClient) CreateBulk(builders ...*ChangeCreate) *ChangeCreateBulk {
	return &ChangeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChangeClient) MapCreateBulk(slice any, setFunc func(*ChangeCreate, int)) *ChangeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChangeCreateBulk{err: fmt.Errorf("calling to ChangeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChangeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChangeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Change.
func (c *ChangeClient) Update() *ChangeUpdate {
	mutation := newChangeMutation(c.config, OpUpdate)
	return &ChangeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChangeClient) UpdateOne(_m *Change) *ChangeUpdateOne {
	mutation := newChangeMutation(c.config, OpUpdateOne, withChange(_m))
	return &ChangeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChangeClient) UpdateOneID(id string) *ChangeUpdateOne {
	mutation := newChangeMutation(c.config, OpUpdateOne, withChangeID(id))
	return &ChangeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Change.
func (c *ChangeClient) Delete() *ChangeDelete {
	mutation := newChangeMutation(c.config, OpDelete)
	return &ChangeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChangeClient) DeleteOne(_m *Change) *ChangeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChangeClient) DeleteOneID(id string) *ChangeDeleteOne {
	builder := c.Delete().Where(change.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChangeDeleteOne{builder}
}

// Query returns a query builder for Change.
func (c *ChangeClient) Query() *ChangeQuery {
	return &ChangeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChange},
		inters: c.Interceptors(),
	}
}

// Get returns a Change entity by its id.
func (c *ChangeClient) Get(ctx context.Context, id string) (*Change, error) {
	return c.Query().Where(change.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChangeClient) GetX(ctx context.Context, id string) *Change {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a Change.
func (c *ChangeClient) QueryProject(_m *Change) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(change.Table, change.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, change.ProjectTable, change.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChangeClient) Hooks() []Hook {
	hooks := c.hooks.Change
	return append(hooks[:len(hooks):len(hooks)], change.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ChangeClient) Interceptors() []Interceptor {
	return c.inters.Change
}

func (c *ChangeClient) mutate(ctx context.Context, m *ChangeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChangeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChangeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChangeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChangeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Change mutation op: %q", m.Op())
	}
}

// ContentObjectClient is a client for the ContentObject schema.
type ContentObjectClient struct {
	config
}

// NewContentObjectClient returns a client for the ContentObject from the given config.
func NewContentObjectClient(c config) *ContentObjectClient {
	return &ContentObjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contentobject.Hooks(f(g(h())))`.
func (c *ContentObjectClient) Use(hooks ...Hook) {
	c.hooks.ContentObject = append(c.hooks.ContentObject, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contentobject.Intercept(f(g(h())))`.
func (c *ContentObjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.ContentObject = append(c.inters.ContentObject, interceptors...)
}

// Create returns a builder for creating a ContentObject entity.
func (c *ContentObjectClient) Create() *ContentObjectCreate {
	mutation := newContentObjectMutation(c.config, OpCreate)
	return &ContentObjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ContentObject entities.
func (c *ContentObjectClient) CreateBulk(builders ...*ContentObjectCreate) *ContentObjectCreateBulk {
	return &ContentObjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContentObjectClient) MapCreateBulk(slice any, setFunc func(*ContentObjectCreate, int)) *ContentObjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContentObjectCreateBulk{err: fmt.Errorf("calling to ContentObjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContentObjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContentObjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ContentObject.
func (c *ContentObjectClient) Update() *ContentObjectUpdate {
	mutation := newContentObjectMutation(c.config, OpUpdate)
	return &ContentObjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContentObjectClient) UpdateOne(_m *ContentObject) *ContentObjectUpdateOne {
	mutation := newContentObjectMutation(c.config, OpUpdateOne, withContentObject(_m))
	return &ContentObjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContentObjectClient) UpdateOneID(id string) *ContentObjectUpdateOne {
	mutation := newContentObjectMutation(c.config, OpUpdateOne, withContentObjectID(id))
	return &ContentObjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ContentObject.
func (c *ContentObjectClient) Delete() *ContentObjectDelete {
	mutation := newContentObjectMutation(c.config, OpDelete)
	return &ContentObjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContentObjectClient) DeleteOne(_m *ContentObject) *ContentObjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContentObjectClient) DeleteOneID(id string) *ContentObjectDeleteOne {
	builder := c.Delete().Where(contentobject.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContentObjectDeleteOne{builder}
}

// Query returns a query builder for ContentObject.
func (c *ContentObjectClient) Query() *ContentObjectQuery {
	return &ContentObjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContentObject},
		inters: c.Interceptors(),
	}
}

// Get returns a ContentObject entity by its id.
func (c *ContentObjectClient) Get(ctx context.Context, id string) (*ContentObject, error) {
	return c.Query().Where(contentobject.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContentObjectClient) GetX(ctx context.Context, id string) *ContentObject {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a ContentObject.
func (c *ContentObjectClient) QueryProject(_m *ContentObject) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(contentobject.Table, contentobject.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, contentobject.ProjectTable, contentobject.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ContentObjectClient) Hooks() []Hook {
	hooks := c.hooks.ContentObject
	return append(hooks[:len(hooks):len(hooks)], contentobject.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ContentObjectClient) Interceptors() []Interceptor {
	return c.inters.ContentObject
}

func (c *ContentObjectClient) mutate(ctx context.Context, m *ContentObjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContentObjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContentObjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContentObjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContentObjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ContentObject mutation op: %q", m.Op())
	}
}

// EventClient is a client for the Event schema.
type EventClient struct {
	config
}

// NewEventClient returns a client for the Event from the given config.
func NewEventClient(c config) *EventClient {
	return &EventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `event.Hooks(f(g(h())))`.
func (c *EventClient) Use(hooks ...Hook) {
	c.hooks.Event = append(c.hooks.Event, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `event.Intercept(f(g(h())))`.
func (c *EventClient) Intercept(interceptors ...Interceptor) {
	c.inters.Event = append(c.inters.Event, interceptors...)
}

// Create returns a builder for creating a Event entity.
func (c *EventClient) Create() *EventCreate {
	mutation := newEventMutation(c.config, OpCreate)
	return &EventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Event entities.
func (c *EventClient) CreateBulk(builders ...*EventCreate) *EventCreateBulk {
	return &EventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventClient) MapCreateBulk(slice any, setFunc func(*EventCreate, int)) *EventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventCreateBulk{err: fmt.Errorf("calling to EventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Event.
func (c *EventClient) Update() *EventUpdate {
	mutation := newEventMutation(c.config, OpUpdate)
	return &EventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventClient) UpdateOne(_m *Event) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEvent(_m))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventClient) UpdateOneID(id string) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEventID(id))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Event.
func (c *EventClient) Delete() *EventDelete {
	mutation := newEventMutation(c.config, OpDelete)
	return &EventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventClient) DeleteOne(_m *Event) *EventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventClient) DeleteOneID(id string) *EventDeleteOne {
	builder := c.Delete().Where(event.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventDeleteOne{builder}
}

// Query returns a query builder for Event.
func (c *EventClient) Query() *EventQuery {
	return &EventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a Event entity by its id.
func (c *EventClient) Get(ctx context.Context, id string) (*Event, error) {
	return c.Query().Where(event.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventClient) GetX(ctx context.Context, id string) *Event {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a Event.
func (c *EventClient) QueryProject(_m *Event) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, event.ProjectTable, event.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChange queries the change edge of a Event.
func (c *EventClient) QueryChange(_m *Event) *ChangeQuery {
	query := (&ChangeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(change.Table, change.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, event.ChangeTable, event.ChangeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EventClient) Hooks() []Hook {
	hooks := c.hooks.Event
	return append(hooks[:len(hooks):len(hooks)], event.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *EventClient) Interceptors() []Interceptor {
	return c.inters.Event
}

func (c *EventClient) mutate(ctx context.Context, m *EventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Event mutation op: %q", m.Op())
	}
}

// EventRecordPinClient is a client for the EventRecordPin schema.
type EventRecordPinClient struct {
	config
}

// NewEventRecordPinClient returns a client for the EventRecordPin from the given config.
func NewEventRecordPinClient(c config) *EventRecordPinClient {
	return &EventRecordPinClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `eventrecordpin.Hooks(f(g(h())))`.
func (c *EventRecordPinClient) Use(hooks ...Hook) {
	c.hooks.EventRecordPin = append(c.hooks.EventRecordPin, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `eventrecordpin.Intercept(f(g(h())))`.
func (c *EventRecordPinClient) Intercept(interceptors ...Interceptor) {
	c.inters.EventRecordPin = append(c.inters.EventRecordPin, interceptors...)
}

// Create returns a builder for creating a EventRecordPin entity.
func (c *EventRecordPinClient) Create() *EventRecordPinCreate {
	mutation := newEventRecordPinMutation(c.config, OpCreate)
	return &EventRecordPinCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EventRecordPin entities.
func (c *EventRecordPinClient) CreateBulk(builders ...*EventRecordPinCreate) *EventRecordPinCreateBulk {
	return &EventRecordPinCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventRecordPinClient) MapCreateBulk(slice any, setFunc func(*EventRecordPinCreate, int)) *EventRecordPinCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventRecordPinCreateBulk{err: fmt.Errorf("calling to EventRecordPinClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventRecordPinCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventRecordPinCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EventRecordPin.
func (c *EventRecordPinClient) Update() *EventRecordPinUpdate {
	mutation := newEventRecordPinMutation(c.config, OpUpdate)
	return &EventRecordPinUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventRecordPinClient) UpdateOne(_m *EventRecordPin) *EventRecordPinUpdateOne {
	mutation := newEventRecordPinMutation(c.config, OpUpdateOne, withEventRecordPin(_m))
	return &EventRecordPinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventRecordPinClient) UpdateOneID(id string) *EventRecordPinUpdateOne {
	mutation := newEventRecordPinMutation(c.config, OpUpdateOne, withEventRecordPinID(id))
	return &EventRecordPinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EventRecordPin.
func (c *EventRecordPinClient) Delete() *EventRecordPinDelete {
	mutation := newEventRecordPinMutation(c.config, OpDelete)
	return &EventRecordPinDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventRecordPinClient) DeleteOne(_m *EventRecordPin) *EventRecordPinDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventRecordPinClient) DeleteOneID(id string) *EventRecordPinDeleteOne {
	builder := c.Delete().Where(eventrecordpin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventRecordPinDeleteOne{builder}
}

// Query returns a query builder for EventRecordPin.
func (c *EventRecordPinClient) Query() *EventRecordPinQuery {
	return &EventRecordPinQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEventRecordPin},
		inters: c.Interceptors(),
	}
}

// Get returns a EventRecordPin entity by its id.
func (c *EventRecordPinClient) Get(ctx context.Context, id string) (*EventRecordPin, error) {
	return c.Query().Where(eventrecordpin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventRecordPinClient) GetX(ctx context.Context, id string) *EventRecordPin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a EventRecordPin.
func (c *EventRecordPinClient) QueryProject(_m *EventRecordPin) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(eventrecordpin.Table, eventrecordpin.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, eventrecordpin.ProjectTable, eventrecordpin.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvent queries the event edge of a EventRecordPin.
func (c *EventRecordPinClient) QueryEvent(_m *EventRecordPin) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(eventrecordpin.Table, eventrecordpin.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, eventrecordpin.EventTable, eventrecordpin.EventColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRecordVersion queries the record_version edge of a EventRecordPin.
func (c *EventRecordPinClient) QueryRecordVersion(_m *EventRecordPin) *RecordVersionQuery {
	query := (&RecordVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(eventrecordpin.Table, eventrecordpin.FieldID, id),
			sqlgraph.To(recordversion.Table, recordversion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, eventrecordpin.RecordVersionTable, eventrecordpin.RecordVersionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EventRecordPinClient) Hooks() []Hook {
	hooks := c.hooks.EventRecordPin
	return append(hooks[:len(hooks):len(hooks)], eventrecordpin.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *EventRecordPinClient) Interceptors() []Interceptor {
	return c.inters.EventRecordPin
}

func (c *EventRecordPinClient) mutate(ctx context.Context, m *EventRecordPinMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventRecordPinCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventRecordPinUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventRecordPinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventRecordPinDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EventRecordPin mutation op: %q", m.Op())
	}
}

// IterationNoteClient is a client for the IterationNote schema.
type IterationNoteClient struct {
	config
}

// NewIterationNoteClient returns a client for the IterationNote from the given config.
func NewIterationNoteClient(c config) *IterationNoteClient {
	return &IterationNoteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `iterationnote.Hooks(f(g(h())))`.
func (c *IterationNoteClient) Use(hooks ...Hook) {
	c.hooks.IterationNote = append(c.hooks.IterationNote, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `iterationnote.Intercept(f(g(h())))`.
func (c *IterationNoteClient) Intercept(interceptors ...Interceptor) {
	c.inters.IterationNote = append(c.inters.IterationNote, interceptors...)
}

// Create returns a builder for creating a IterationNote entity.
func (c *IterationNoteClient) Create() *IterationNoteCreate {
	mutation := newIterationNoteMutation(c.config, OpCreate)
	return &IterationNoteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IterationNote entities.
func (c *IterationNoteClient) CreateBulk(builders ...*IterationNoteCreate) *IterationNoteCreateBulk {
	return &IterationNoteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IterationNoteClient) MapCreateBulk(slice any, setFunc func(*IterationNoteCreate, int)) *IterationNoteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IterationNoteCreateBulk{err: fmt.Errorf("calling to IterationNoteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IterationNoteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IterationNoteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IterationNote.
func (c *IterationNoteClient) Update() *IterationNoteUpdate {
	mutation := newIterationNoteMutation(c.config, OpUpdate)
	return &IterationNoteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IterationNoteClient) UpdateOne(_m *IterationNote) *IterationNoteUpdateOne {
	mutation := newIterationNoteMutation(c.config, OpUpdateOne, withIterationNote(_m))
	return &IterationNoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IterationNoteClient) UpdateOneID(id string) *IterationNoteUpdateOne {
	mutation := newIterationNoteMutation(c.config, OpUpdateOne, withIterationNoteID(id))
	return &IterationNoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IterationNote.
func (c *IterationNoteClient) Delete() *IterationNoteDelete {
	mutation := newIterationNoteMutation(c.config, OpDelete)
	return &IterationNoteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IterationNoteClient) DeleteOne(_m *IterationNote) *IterationNoteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IterationNoteClient) DeleteOneID(id string) *IterationNoteDeleteOne {
	builder := c.Delete().Where(iterationnote.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IterationNoteDeleteOne{builder}
}

// Query returns a query builder for IterationNote.
func (c *IterationNoteClient) Query() *IterationNoteQuery {
	return &IterationNoteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIterationNote},
		inters: c.Interceptors(),
	}
}

// Get returns a IterationNote entity by its id.
func (c *IterationNoteClient) Get(ctx context.Context, id string) (*IterationNote, error) {
	return c.Query().Where(iterationnote.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IterationNoteClient) GetX(ctx context.Context, id string) *IterationNote {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a IterationNote.
func (c *IterationNoteClient) QueryProject(_m *IterationNote) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(iterationnote.Table, iterationnote.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, iterationnote.ProjectTable, iterationnote.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChange queries the change edge of a IterationNote.
func (c *IterationNoteClient) QueryChange(_m *IterationNote) *ChangeQuery {
	query := (&ChangeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(iterationnote.Table, iterationnote.FieldID, id),
			sqlgraph.To(change.Table, change.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, iterationnote.ChangeTable, iterationnote.ChangeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvent queries the event edge of a IterationNote.
func (c *IterationNoteClient) QueryEvent(_m *IterationNote) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(iterationnote.Table, iterationnote.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, iterationnote.EventTable, iterationnote.EventColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IterationNoteClient) Hooks() []Hook {
	hooks := c.hooks.IterationNote
	return append(hooks[:len(hooks):len(hooks)], iterationnote.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *IterationNoteClient) Interceptors() []Interceptor {
	return c.inters.IterationNote
}

func (c *IterationNoteClient) mutate(ctx context.Context, m *IterationNoteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IterationNoteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IterationNoteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IterationNoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IterationNoteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IterationNote mutation op: %q", m.Op())
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(_m *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(_m))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id string) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(_m *Project) *ProjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id string) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id string) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id string) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	hooks := c.hooks.Project
	return append(hooks[:len(hooks):len(hooks)], project.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// ProjectPathClient is a client for the ProjectPath schema.
type ProjectPathClient struct {
	config
}

// NewProjectPathClient returns a client for the ProjectPath from the given config.
func NewProjectPathClient(c config) *ProjectPathClient {
	return &ProjectPathClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `projectpath.Hooks(f(g(h())))`.
func (c *ProjectPathClient) Use(hooks ...Hook) {
	c.hooks.ProjectPath = append(c.hooks.ProjectPath, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `projectpath.Intercept(f(g(h())))`.
func (c *ProjectPathClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProjectPath = append(c.inters.ProjectPath, interceptors...)
}

// Create returns a builder for creating a ProjectPath entity.
func (c *ProjectPathClient) Create() *ProjectPathCreate {
	mutation := newProjectPathMutation(c.config, OpCreate)
	return &ProjectPathCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProjectPath entities.
func (c *ProjectPathClient) CreateBulk(builders ...*ProjectPathCreate) *ProjectPathCreateBulk {
	return &ProjectPathCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectPathClient) MapCreateBulk(slice any, setFunc func(*ProjectPathCreate, int)) *ProjectPathCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectPathCreateBulk{err: fmt.Errorf("calling to ProjectPathClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectPathCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectPathCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProjectPath.
func (c *ProjectPathClient) Update() *ProjectPathUpdate {
	mutation := newProjectPathMutation(c.config, OpUpdate)
	return &ProjectPathUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectPathClient) UpdateOne(_m *ProjectPath) *ProjectPathUpdateOne {
	mutation := newProjectPathMutation(c.config, OpUpdateOne, withProjectPath(_m))
	return &ProjectPathUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectPathClient) UpdateOneID(id string) *ProjectPathUpdateOne {
	mutation := newProjectPathMutation(c.config, OpUpdateOne, withProjectPathID(id))
	return &ProjectPathUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProjectPath.
func (c *ProjectPathClient) Delete() *ProjectPathDelete {
	mutation := newProjectPathMutation(c.config, OpDelete)
	return &ProjectPathDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectPathClient) DeleteOne(_m *ProjectPath) *ProjectPathDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectPathClient) DeleteOneID(id string) *ProjectPathDeleteOne {
	builder := c.Delete().Where(projectpath.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectPathDeleteOne{builder}
}

// Query returns a query builder for ProjectPath.
func (c *ProjectPathClient) Query() *ProjectPathQuery {
	return &ProjectPathQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProjectPath},
		inters: c.Interceptors(),
	}
}

// Get returns a ProjectPath entity by its id.
func (c *ProjectPathClient) Get(ctx context.Context, id string) (*ProjectPath, error) {
	return c.Query().Where(projectpath.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectPathClient) GetX(ctx context.Context, id string) *ProjectPath {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a ProjectPath.
func (c *ProjectPathClient) QueryProject(_m *ProjectPath) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(projectpath.Table, projectpath.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, projectpath.ProjectTable, projectpath.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectPathClient) Hooks() []Hook {
	hooks := c.hooks.ProjectPath
	return append(hooks[:len(hooks):len(hooks)], projectpath.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ProjectPathClient) Interceptors() []Interceptor {
	return c.inters.ProjectPath
}

func (c *ProjectPathClient) mutate(ctx context.Context, m *ProjectPathMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectPathCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectPathUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectPathUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectPathDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProjectPath mutation op: %q", m.Op())
	}
}

// RecordClient is a client for the Record schema.
type RecordClient struct {
	config
}

// NewRecordClient returns a client for the Record from the given config.
func NewRecordClient(c config) *RecordClient {
	return &RecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `record.Hooks(f(g(h())))`.
func (c *RecordClient) Use(hooks ...Hook) {
	c.hooks.Record = append(c.hooks.Record, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `record.Intercept(f(g(h())))`.
func (c *RecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.Record = append(c.inters.Record, interceptors...)
}

// Create returns a builder for creating a Record entity.
func (c *RecordClient) Create() *RecordCreate {
	mutation := newRecordMutation(c.config, OpCreate)
	return &RecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Record entities.
func (c *RecordClient) CreateBulk(builders ...*RecordCreate) *RecordCreateBulk {
	return &RecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordClient) MapCreateBulk(slice any, setFunc func(*RecordCreate, int)) *RecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordCreateBulk{err: fmt.Errorf("calling to RecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Record.
func (c *RecordClient) Update() *RecordUpdate {
	mutation := newRecordMutation(c.config, OpUpdate)
	return &RecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordClient) UpdateOne(_m *Record) *RecordUpdateOne {
	mutation := newRecordMutation(c.config, OpUpdateOne, withRecord(_m))
	return &RecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordClient) UpdateOneID(id string) *RecordUpdateOne {
	mutation := newRecordMutation(c.config, OpUpdateOne, withRecordID(id))
	return &RecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Record.
func (c *RecordClient) Delete() *RecordDelete {
	mutation := newRecordMutation(c.config, OpDelete)
	return &RecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordClient) DeleteOne(_m *Record) *RecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordClient) DeleteOneID(id string) *RecordDeleteOne {
	builder := c.Delete().Where(record.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordDeleteOne{builder}
}

// Query returns a query builder for Record.
func (c *RecordClient) Query() *RecordQuery {
	return &RecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a Record entity by its id.
func (c *RecordClient) Get(ctx context.Context, id string) (*Record, error) {
	return c.Query().Where(record.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordClient) GetX(ctx context.Context, id string) *Record {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a Record.
func (c *RecordClient) QueryProject(_m *Record) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(record.Table, record.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, record.ProjectTable, record.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordClient) Hooks() []Hook {
	hooks := c.hooks.Record
	return append(hooks[:len(hooks):len(hooks)], record.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *RecordClient) Interceptors() []Interceptor {
	return c.inters.Record
}

func (c *RecordClient) mutate(ctx context.Context, m *RecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Record mutation op: %q", m.Op())
	}
}

// RecordBranchStateClient is a client for the RecordBranchState schema.
type RecordBranchStateClient struct {
	config
}

// NewRecordBranchStateClient returns a client for the RecordBranchState from the given config.
func NewRecordBranchStateClient(c config) *RecordBranchStateClient {
	return &RecordBranchStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordbranchstate.Hooks(f(g(h())))`.
func (c *RecordBranchStateClient) Use(hooks ...Hook) {
	c.hooks.RecordBranchState = append(c.hooks.RecordBranchState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recordbranchstate.Intercept(f(g(h())))`.
func (c *RecordBranchStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.RecordBranchState = append(c.inters.RecordBranchState, interceptors...)
}

// Create returns a builder for creating a RecordBranchState entity.
func (c *RecordBranchStateClient) Create() *RecordBranchStateCreate {
	mutation := newRecordBranchStateMutation(c.config, OpCreate)
	return &RecordBranchStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordBranchState entities.
func (c *RecordBranchStateClient) CreateBulk(builders ...*RecordBranchStateCreate) *RecordBranchStateCreateBulk {
	return &RecordBranchStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordBranchStateClient) MapCreateBulk(slice any, setFunc func(*RecordBranchStateCreate, int)) *RecordBranchStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordBranchStateCreateBulk{err: fmt.Errorf("calling to RecordBranchStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordBranchStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordBranchStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordBranchState.
func (c *RecordBranchStateClient) Update() *RecordBranchStateUpdate {
	mutation := newRecordBranchStateMutation(c.config, OpUpdate)
	return &RecordBranchStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordBranchStateClient) UpdateOne(_m *RecordBranchState) *RecordBranchStateUpdateOne {
	mutation := newRecordBranchStateMutation(c.config, OpUpdateOne, withRecordBranchState(_m))
	return &RecordBranchStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordBranchStateClient) UpdateOneID(id string) *RecordBranchStateUpdateOne {
	mutation := newRecordBranchStateMutation(c.config, OpUpdateOne, withRecordBranchStateID(id))
	return &RecordBranchStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordBranchState.
func (c *RecordBranchStateClient) Delete() *RecordBranchStateDelete {
	mutation := newRecordBranchStateMutation(c.config, OpDelete)
	return &RecordBranchStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordBranchStateClient) DeleteOne(_m *RecordBranchState) *RecordBranchStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordBranchStateClient) DeleteOneID(id string) *RecordBranchStateDeleteOne {
	builder := c.Delete().Where(recordbranchstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordBranchStateDeleteOne{builder}
}

// Query returns a query builder for RecordBranchState.
func (c *RecordBranchStateClient) Query() *RecordBranchStateQuery {
	return &RecordBranchStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecordBranchState},
		inters: c.Interceptors(),
	}
}

// Get returns a RecordBranchState entity by its id.
func (c *RecordBranchStateClient) Get(ctx context.Context, id string) (*RecordBranchState, error) {
	return c.Query().Where(recordbranchstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordBranchStateClient) GetX(ctx context.Context, id string) *RecordBranchState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a RecordBranchState.
func (c *RecordBranchStateClient) QueryProject(_m *RecordBranchState) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordbranchstate.Table, recordbranchstate.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordbranchstate.ProjectTable, recordbranchstate.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRecord queries the record edge of a RecordBranchState.
func (c *RecordBranchStateClient) QueryRecord(_m *RecordBranchState) *RecordQuery {
	query := (&RecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordbranchstate.Table, recordbranchstate.FieldID, id),
			sqlgraph.To(record.Table, record.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordbranchstate.RecordTable, recordbranchstate.RecordColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCurrentVersion queries the current_version edge of a RecordBranchState.
func (c *RecordBranchStateClient) QueryCurrentVersion(_m *RecordBranchState) *RecordVersionQuery {
	query := (&RecordVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordbranchstate.Table, recordbranchstate.FieldID, id),
			sqlgraph.To(recordversion.Table, recordversion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordbranchstate.CurrentVersionTable, recordbranchstate.CurrentVersionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordBranchStateClient) Hooks() []Hook {
	hooks := c.hooks.RecordBranchState
	return append(hooks[:len(hooks):len(hooks)], recordbranchstate.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *RecordBranchStateClient) Interceptors() []Interceptor {
	return c.inters.RecordBranchState
}

func (c *RecordBranchStateClient) mutate(ctx context.Context, m *RecordBranchStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordBranchStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordBranchStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordBranchStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordBranchStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RecordBranchState mutation op: %q", m.Op())
	}
}

// RecordVersionClient is a client for the RecordVersion schema.
type RecordVersionClient struct {
	config
}

// NewRecordVersionClient returns a client for the RecordVersion from the given config.
func NewRecordVersionClient(c config) *RecordVersionClient {
	return &RecordVersionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordversion.Hooks(f(g(h())))`.
func (c *RecordVersionClient) Use(hooks ...Hook) {
	c.hooks.RecordVersion = append(c.hooks.RecordVersion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recordversion.Intercept(f(g(h())))`.
func (c *RecordVersionClient) Intercept(interceptors ...Interceptor) {
	c.inters.RecordVersion = append(c.inters.RecordVersion, interceptors...)
}

// Create returns a builder for creating a RecordVersion entity.
func (c *RecordVersionClient) Create() *RecordVersionCreate {
	mutation := newRecordVersionMutation(c.config, OpCreate)
	return &RecordVersionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordVersion entities.
func (c *RecordVersionClient) CreateBulk(builders ...*RecordVersionCreate) *RecordVersionCreateBulk {
	return &RecordVersionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordVersionClient) MapCreateBulk(slice any, setFunc func(*RecordVersionCreate, int)) *RecordVersionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordVersionCreateBulk{err: fmt.Errorf("calling to RecordVersionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordVersionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordVersionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordVersion.
func (c *RecordVersionClient) Update() *RecordVersionUpdate {
	mutation := newRecordVersionMutation(c.config, OpUpdate)
	return &RecordVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordVersionClient) UpdateOne(_m *RecordVersion) *RecordVersionUpdateOne {
	mutation := newRecordVersionMutation(c.config, OpUpdateOne, withRecordVersion(_m))
	return &RecordVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordVersionClient) UpdateOneID(id string) *RecordVersionUpdateOne {
	mutation := newRecordVersionMutation(c.config, OpUpdateOne, withRecordVersionID(id))
	return &RecordVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordVersion.
func (c *RecordVersionClient) Delete() *RecordVersionDelete {
	mutation := newRecordVersionMutation(c.config, OpDelete)
	return &RecordVersionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordVersionClient) DeleteOne(_m *RecordVersion) *RecordVersionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordVersionClient) DeleteOneID(id string) *RecordVersionDeleteOne {
	builder := c.Delete().Where(recordversion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordVersionDeleteOne{builder}
}

// Query returns a query builder for RecordVersion.
func (c *RecordVersionClient) Query() *RecordVersionQuery {
	return &RecordVersionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecordVersion},
		inters: c.Interceptors(),
	}
}

// Get returns a RecordVersion entity by its id.
func (c *RecordVersionClient) Get(ctx context.Context, id string) (*RecordVersion, error) {
	return c.Query().Where(recordversion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordVersionClient) GetX(ctx context.Context, id string) *RecordVersion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a RecordVersion.
func (c *RecordVersionClient) QueryProject(_m *RecordVersion) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversion.Table, recordversion.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversion.ProjectTable, recordversion.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRecord queries the record edge of a RecordVersion.
func (c *RecordVersionClient) QueryRecord(_m *RecordVersion) *RecordQuery {
	query := (&RecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversion.Table, recordversion.FieldID, id),
			sqlgraph.To(record.Table, record.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversion.RecordTable, recordversion.RecordColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryContentObject queries the content_object edge of a RecordVersion.
func (c *RecordVersionClient) QueryContentObject(_m *RecordVersion) *ContentObjectQuery {
	query := (&ContentObjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversion.Table, recordversion.FieldID, id),
			sqlgraph.To(contentobject.Table, contentobject.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversion.ContentObjectTable, recordversion.ContentObjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordVersionClient) Hooks() []Hook {
	hooks := c.hooks.RecordVersion
	return append(hooks[:len(hooks):len(hooks)], recordversion.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *RecordVersionClient) Interceptors() []Interceptor {
	return c.inters.RecordVersion
}

func (c *RecordVersionClient) mutate(ctx context.Context, m *RecordVersionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordVersionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordVersionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RecordVersion mutation op: %q", m.Op())
	}
}

// RecordVersionRefClient is a client for the RecordVersionRef schema.
type RecordVersionRefClient struct {
	config
}

// NewRecordVersionRefClient returns a client for the RecordVersionRef from the given config.
func NewRecordVersionRefClient(c config) *RecordVersionRefClient {
	return &RecordVersionRefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordversionref.Hooks(f(g(h())))`.
func (c *RecordVersionRefClient) Use(hooks ...Hook) {
	c.hooks.RecordVersionRef = append(c.hooks.RecordVersionRef, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recordversionref.Intercept(f(g(h())))`.
func (c *RecordVersionRefClient) Intercept(interceptors ...Interceptor) {
	c.inters.RecordVersionRef = append(c.inters.RecordVersionRef, interceptors...)
}

// Create returns a builder for creating a RecordVersionRef entity.
func (c *RecordVersionRefClient) Create() *RecordVersionRefCreate {
	mutation := newRecordVersionRefMutation(c.config, OpCreate)
	return &RecordVersionRefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordVersionRef entities.
func (c *RecordVersionRefClient) CreateBulk(builders ...*RecordVersionRefCreate) *RecordVersionRefCreateBulk {
	return &RecordVersionRefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordVersionRefClient) MapCreateBulk(slice any, setFunc func(*RecordVersionRefCreate, int)) *RecordVersionRefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordVersionRefCreateBulk{err: fmt.Errorf("calling to RecordVersionRefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordVersionRefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordVersionRefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordVersionRef.
func (c *RecordVersionRefClient) Update() *RecordVersionRefUpdate {
	mutation := newRecordVersionRefMutation(c.config, OpUpdate)
	return &RecordVersionRefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordVersionRefClient) UpdateOne(_m *RecordVersionRef) *RecordVersionRefUpdateOne {
	mutation := newRecordVersionRefMutation(c.config, OpUpdateOne, withRecordVersionRef(_m))
	return &RecordVersionRefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordVersionRefClient) UpdateOneID(id string) *RecordVersionRefUpdateOne {
	mutation := newRecordVersionRefMutation(c.config, OpUpdateOne, withRecordVersionRefID(id))
	return &RecordVersionRefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordVersionRef.
func (c *RecordVersionRefClient) Delete() *RecordVersionRefDelete {
	mutation := newRecordVersionRefMutation(c.config, OpDelete)
	return &RecordVersionRefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordVersionRefClient) DeleteOne(_m *RecordVersionRef) *RecordVersionRefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordVersionRefClient) DeleteOneID(id string) *RecordVersionRefDeleteOne {
	builder := c.Delete().Where(recordversionref.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordVersionRefDeleteOne{builder}
}

// Query returns a query builder for RecordVersionRef.
func (c *RecordVersionRefClient) Query() *RecordVersionRefQuery {
	return &RecordVersionRefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecordVersionRef},
		inters: c.Interceptors(),
	}
}

// Get returns a RecordVersionRef entity by its id.
func (c *RecordVersionRefClient) Get(ctx context.Context, id string) (*RecordVersionRef, error) {
	return c.Query().Where(recordversionref.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordVersionRefClient) GetX(ctx context.Context, id string) *RecordVersionRef {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a RecordVersionRef.
func (c *RecordVersionRefClient) QueryProject(_m *RecordVersionRef) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversionref.Table, recordversionref.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversionref.ProjectTable, recordversionref.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRecordVersion queries the record_version edge of a RecordVersionRef.
func (c *RecordVersionRefClient) QueryRecordVersion(_m *RecordVersionRef) *RecordVersionQuery {
	query := (&RecordVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversionref.Table, recordversionref.FieldID, id),
			sqlgraph.To(recordversion.Table, recordversion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversionref.RecordVersionTable, recordversionref.RecordVersionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordVersionRefClient) Hooks() []Hook {
	hooks := c.hooks.RecordVersionRef
	return append(hooks[:len(hooks):len(hooks)], recordversionref.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *RecordVersionRefClient) Interceptors() []Interceptor {
	return c.inters.RecordVersionRef
}

func (c *RecordVersionRefClient) mutate(ctx context.Context, m *RecordVersionRefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordVersionRefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordVersionRefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordVersionRefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordVersionRefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RecordVersionRef mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Change, ContentObject, Event, EventRecordPin, IterationNote, Project,
		ProjectPath, Record, RecordBranchState, RecordVersion,
		RecordVersionRef []ent.Hook
	}
	inters struct {
		Change, ContentObject, Event, EventRecordPin, IterationNote, Project,
		ProjectPath, Record, RecordBranchState, RecordVersion,
		RecordVersionRef []ent.Interceptor
	}
)
