// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/event"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventCreate) SetCreatedAt(v string) *EventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedAt(v *string) *EventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventCreate) SetUpdatedAt(v string) *EventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedAt(v *string) *EventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *EventCreate) SetProjectID(v string) *EventCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetChangeID sets the "change_id" field.
func (_c *EventCreate) SetChangeID(v string) *EventCreate {
	_c.mutation.SetChangeID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *EventCreate) SetPosition(v int64) *EventCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetType sets the "type" field.
func (_c *EventCreate) SetType(v string) *EventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *EventCreate) SetPayload(v string) *EventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *EventCreate) SetOccurredAt(v string) *EventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableOccurredAt(v *string) *EventCreate {
	if v != nil {
		_c.SetOccurredAt(*v)
	}
	return _c
}

// SetAgentKind sets the "agent_kind" field.
func (_c *EventCreate) SetAgentKind(v string) *EventCreate {
	_c.mutation.SetAgentKind(v)
	return _c
}

// SetNillableAgentKind sets the "agent_kind" field if the given value is not nil.
func (_c *EventCreate) SetNillableAgentKind(v *string) *EventCreate {
	if v != nil {
		_c.SetAgentKind(*v)
	}
	return _c
}

// SetAgentName sets the "agent_name" field.
func (_c *EventCreate) SetAgentName(v string) *EventCreate {
	_c.mutation.SetAgentName(v)
	return _c
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_c *EventCreate) SetNillableAgentName(v *string) *EventCreate {
	if v != nil {
		_c.SetAgentName(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *EventCreate) SetSessionID(v string) *EventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableSessionID(v *string) *EventCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetIdempotencyHash sets the "idempotency_hash" field.
func (_c *EventCreate) SetIdempotencyHash(v string) *EventCreate {
	_c.mutation.SetIdempotencyHash(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v string) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventCreate) SetNillableID(v *string) *EventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *EventCreate) SetProject(v *Project) *EventCreate {
	return _c.SetProjectID(v.ID)
}

// SetChange sets the "change" edge to the Change entity.
func (_c *EventCreate) SetChange(v *Change) *EventCreate {
	return _c.SetChangeID(v.ID)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if event.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if event.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		if event.DefaultOccurredAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultOccurredAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultOccurredAt()
		_c.mutation.SetOccurredAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if event.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultID (forgotten import ent/runtime?)")
		}
		v := event.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Event.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Event.updated_at"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Event.project_id"`)}
	}
	if _, ok := _c.mutation.ChangeID(); !ok {
		return &ValidationError{Name: "change_id", err: errors.New(`ent: missing required field "Event.change_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "Event.position"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Event.type"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Event.payload"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "Event.occurred_at"`)}
	}
	if _, ok := _c.mutation.IdempotencyHash(); !ok {
		return &ValidationError{Name: "idempotency_hash", err: errors.New(`ent: missing required field "Event.idempotency_hash"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Event.project"`)}
	}
	if len(_c.mutation.ChangeIDs()) == 0 {
		return &ValidationError{Name: "change", err: errors.New(`ent: missing required edge "Event.change"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Event.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(event.FieldPosition, field.TypeInt64, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(event.FieldOccurredAt, field.TypeString, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.AgentKind(); ok {
		_spec.SetField(event.FieldAgentKind, field.TypeString, value)
		_node.AgentKind = value
	}
	if value, ok := _c.mutation.AgentName(); ok {
		_spec.SetField(event.FieldAgentName, field.TypeString, value)
		_node.AgentName = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(event.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.IdempotencyHash(); ok {
		_spec.SetField(event.FieldIdempotencyHash, field.TypeString, value)
		_node.IdempotencyHash = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ChangeTable,
			Columns: []string{event.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChangeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
