// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/event"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
)

// Event is the model entity for the Event schema.
type Event struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt string `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// ChangeID holds the value of the "change_id" field.
	ChangeID string `json:"change_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int64 `json:"position,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt string `json:"occurred_at,omitempty"`
	// AgentKind holds the value of the "agent_kind" field.
	AgentKind string `json:"agent_kind,omitempty"`
	// AgentName holds the value of the "agent_name" field.
	AgentName string `json:"agent_name,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// IdempotencyHash holds the value of the "idempotency_hash" field.
	IdempotencyHash string `json:"idempotency_hash,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventQuery when eager-loading is set.
	Edges        EventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventEdges holds the relations/edges for other nodes in the graph.
type EventEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Change holds the value of the change edge.
	Change *Change `json:"change,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// ChangeOrErr returns the Change value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) ChangeOrErr() (*Change, error) {
	if e.Change != nil {
		return e.Change, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: change.Label}
	}
	return nil, &NotLoadedError{edge: "change"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Event) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case event.FieldPosition:
			values[i] = new(sql.NullInt64)
		case event.FieldID, event.FieldCreatedAt, event.FieldUpdatedAt, event.FieldProjectID, event.FieldChangeID, event.FieldType, event.FieldPayload, event.FieldOccurredAt, event.FieldAgentKind, event.FieldAgentName, event.FieldSessionID, event.FieldIdempotencyHash:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Event fields.
func (_m *Event) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case event.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case event.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case event.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.String
			}
		case event.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		case event.FieldChangeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_id", values[i])
			} else if value.Valid {
				_m.ChangeID = value.String
			}
		case event.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = value.Int64
			}
		case event.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case event.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case event.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.String
			}
		case event.FieldAgentKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_kind", values[i])
			} else if value.Valid {
				_m.AgentKind = value.String
			}
		case event.FieldAgentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_name", values[i])
			} else if value.Valid {
				_m.AgentName = value.String
			}
		case event.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case event.FieldIdempotencyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_hash", values[i])
			} else if value.Valid {
				_m.IdempotencyHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Event.
// This includes values selected through modifiers, order, etc.
func (_m *Event) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Event entity.
func (_m *Event) QueryProject() *ProjectQuery {
	return NewEventClient(_m.config).QueryProject(_m)
}

// QueryChange queries the "change" edge of the Event entity.
func (_m *Event) QueryChange() *ChangeQuery {
	return NewEventClient(_m.config).QueryChange(_m)
}

// Update returns a builder for updating this Event.
// Note that you need to call Event.Unwrap() before calling this method if this Event
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Event) Update() *EventUpdateOne {
	return NewEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Event entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Event) Unwrap() *Event {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Event is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Event) String() string {
	var builder strings.Builder
	builder.WriteString("Event(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("change_id=")
	builder.WriteString(_m.ChangeID)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt)
	builder.WriteString(", ")
	builder.WriteString("agent_kind=")
	builder.WriteString(_m.AgentKind)
	builder.WriteString(", ")
	builder.WriteString("agent_name=")
	builder.WriteString(_m.AgentName)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("idempotency_hash=")
	builder.WriteString(_m.IdempotencyHash)
	builder.WriteByte(')')
	return builder.String()
}

// Events is a parsable slice of Event.
type Events []*Event
