// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/event"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdate) SetUpdatedAt(v string) *EventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUpdatedAt(v *string) *EventUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EventUpdate) SetProjectID(v string) *EventUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableProjectID(v *string) *EventUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetChangeID sets the "change_id" field.
func (_u *EventUpdate) SetChangeID(v string) *EventUpdate {
	_u.mutation.SetChangeID(v)
	return _u
}

// SetNillableChangeID sets the "change_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableChangeID(v *string) *EventUpdate {
	if v != nil {
		_u.SetChangeID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *EventUpdate) SetPosition(v int64) *EventUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePosition(v *int64) *EventUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *EventUpdate) AddPosition(v int64) *EventUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetType sets the "type" field.
func (_u *EventUpdate) SetType(v string) *EventUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableType(v *string) *EventUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventUpdate) SetPayload(v string) *EventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePayload(v *string) *EventUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *EventUpdate) SetOccurredAt(v string) *EventUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *EventUpdate) SetNillableOccurredAt(v *string) *EventUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetAgentKind sets the "agent_kind" field.
func (_u *EventUpdate) SetAgentKind(v string) *EventUpdate {
	_u.mutation.SetAgentKind(v)
	return _u
}

// SetNillableAgentKind sets the "agent_kind" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAgentKind(v *string) *EventUpdate {
	if v != nil {
		_u.SetAgentKind(*v)
	}
	return _u
}

// ClearAgentKind clears the value of the "agent_kind" field.
func (_u *EventUpdate) ClearAgentKind() *EventUpdate {
	_u.mutation.ClearAgentKind()
	return _u
}

// SetAgentName sets the "agent_name" field.
func (_u *EventUpdate) SetAgentName(v string) *EventUpdate {
	_u.mutation.SetAgentName(v)
	return _u
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAgentName(v *string) *EventUpdate {
	if v != nil {
		_u.SetAgentName(*v)
	}
	return _u
}

// ClearAgentName clears the value of the "agent_name" field.
func (_u *EventUpdate) ClearAgentName() *EventUpdate {
	_u.mutation.ClearAgentName()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *EventUpdate) SetSessionID(v string) *EventUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSessionID(v *string) *EventUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *EventUpdate) ClearSessionID() *EventUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetIdempotencyHash sets the "idempotency_hash" field.
func (_u *EventUpdate) SetIdempotencyHash(v string) *EventUpdate {
	_u.mutation.SetIdempotencyHash(v)
	return _u
}

// SetNillableIdempotencyHash sets the "idempotency_hash" field if the given value is not nil.
func (_u *EventUpdate) SetNillableIdempotencyHash(v *string) *EventUpdate {
	if v != nil {
		_u.SetIdempotencyHash(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EventUpdate) SetProject(v *Project) *EventUpdate {
	return _u.SetProjectID(v.ID)
}

// SetChange sets the "change" edge to the Change entity.
func (_u *EventUpdate) SetChange(v *Change) *EventUpdate {
	return _u.SetChangeID(v.ID)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EventUpdate) ClearProject() *EventUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearChange clears the "change" edge to the Change entity.
func (_u *EventUpdate) ClearChange() *EventUpdate {
	_u.mutation.ClearChange()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.project"`)
	}
	if _u.mutation.ChangeCleared() && len(_u.mutation.ChangeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.change"`)
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(event.FieldPosition, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(event.FieldPosition, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(event.FieldOccurredAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentKind(); ok {
		_spec.SetField(event.FieldAgentKind, field.TypeString, value)
	}
	if _u.mutation.AgentKindCleared() {
		_spec.ClearField(event.FieldAgentKind, field.TypeString)
	}
	if value, ok := _u.mutation.AgentName(); ok {
		_spec.SetField(event.FieldAgentName, field.TypeString, value)
	}
	if _u.mutation.AgentNameCleared() {
		_spec.ClearField(event.FieldAgentName, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(event.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(event.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyHash(); ok {
		_spec.SetField(event.FieldIdempotencyHash, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ChangeTable,
			Columns: []string{event.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ChangeTable,
			Columns: []string{event.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdateOne) SetUpdatedAt(v string) *EventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUpdatedAt(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EventUpdateOne) SetProjectID(v string) *EventUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableProjectID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetChangeID sets the "change_id" field.
func (_u *EventUpdateOne) SetChangeID(v string) *EventUpdateOne {
	_u.mutation.SetChangeID(v)
	return _u
}

// SetNillableChangeID sets the "change_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableChangeID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetChangeID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *EventUpdateOne) SetPosition(v int64) *EventUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePosition(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *EventUpdateOne) AddPosition(v int64) *EventUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetType sets the "type" field.
func (_u *EventUpdateOne) SetType(v string) *EventUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableType(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventUpdateOne) SetPayload(v string) *EventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePayload(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *EventUpdateOne) SetOccurredAt(v string) *EventUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableOccurredAt(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetAgentKind sets the "agent_kind" field.
func (_u *EventUpdateOne) SetAgentKind(v string) *EventUpdateOne {
	_u.mutation.SetAgentKind(v)
	return _u
}

// SetNillableAgentKind sets the "agent_kind" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAgentKind(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetAgentKind(*v)
	}
	return _u
}

// ClearAgentKind clears the value of the "agent_kind" field.
func (_u *EventUpdateOne) ClearAgentKind() *EventUpdateOne {
	_u.mutation.ClearAgentKind()
	return _u
}

// SetAgentName sets the "agent_name" field.
func (_u *EventUpdateOne) SetAgentName(v string) *EventUpdateOne {
	_u.mutation.SetAgentName(v)
	return _u
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAgentName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetAgentName(*v)
	}
	return _u
}

// ClearAgentName clears the value of the "agent_name" field.
func (_u *EventUpdateOne) ClearAgentName() *EventUpdateOne {
	_u.mutation.ClearAgentName()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *EventUpdateOne) SetSessionID(v string) *EventUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSessionID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *EventUpdateOne) ClearSessionID() *EventUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetIdempotencyHash sets the "idempotency_hash" field.
func (_u *EventUpdateOne) SetIdempotencyHash(v string) *EventUpdateOne {
	_u.mutation.SetIdempotencyHash(v)
	return _u
}

// SetNillableIdempotencyHash sets the "idempotency_hash" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableIdempotencyHash(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetIdempotencyHash(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EventUpdateOne) SetProject(v *Project) *EventUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetChange sets the "change" edge to the Change entity.
func (_u *EventUpdateOne) SetChange(v *Change) *EventUpdateOne {
	return _u.SetChangeID(v.ID)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EventUpdateOne) ClearProject() *EventUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearChange clears the "change" edge to the Change entity.
func (_u *EventUpdateOne) ClearChange() *EventUpdateOne {
	_u.mutation.ClearChange()
	return _u
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.project"`)
	}
	if _u.mutation.ChangeCleared() && len(_u.mutation.ChangeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.change"`)
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(event.FieldPosition, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(event.FieldPosition, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(event.FieldOccurredAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentKind(); ok {
		_spec.SetField(event.FieldAgentKind, field.TypeString, value)
	}
	if _u.mutation.AgentKindCleared() {
		_spec.ClearField(event.FieldAgentKind, field.TypeString)
	}
	if value, ok := _u.mutation.AgentName(); ok {
		_spec.SetField(event.FieldAgentName, field.TypeString, value)
	}
	if _u.mutation.AgentNameCleared() {
		_spec.ClearField(event.FieldAgentName, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(event.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(event.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyHash(); ok {
		_spec.SetField(event.FieldIdempotencyHash, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ProjectTable,
			Columns: []string{event.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ChangeTable,
			Columns: []string{event.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   event.ChangeTable,
			Columns: []string{event.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
