// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/event"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/iterationnote"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
)

// IterationNoteQuery is the builder for querying IterationNote entities.
type IterationNoteQuery struct {
	config
	ctx         *QueryContext
	order       []iterationnote.OrderOption
	inters      []Interceptor
	predicates  []predicate.IterationNote
	withProject *ProjectQuery
	withChange  *ChangeQuery
	withEvent   *EventQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IterationNoteQuery builder.
func (_q *IterationNoteQuery) Where(ps ...predicate.IterationNote) *IterationNoteQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *IterationNoteQuery) Limit(limit int) *IterationNoteQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *IterationNoteQuery) Offset(offset int) *IterationNoteQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IterationNoteQuery) Unique(unique bool) *IterationNoteQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *IterationNoteQuery) Order(o ...iterationnote.OrderOption) *IterationNoteQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *IterationNoteQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(iterationnote.Table, iterationnote.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, iterationnote.ProjectTable, iterationnote.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChange chains the current query on the "change" edge.
func (_q *IterationNoteQuery) QueryChange() *ChangeQuery {
	query := (&ChangeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(iterationnote.Table, iterationnote.FieldID, selector),
			sqlgraph.To(change.Table, change.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, iterationnote.ChangeTable, iterationnote.ChangeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvent chains the current query on the "event" edge.
func (_q *IterationNoteQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(iterationnote.Table, iterationnote.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, iterationnote.EventTable, iterationnote.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IterationNote entity from the query.
// Returns a *NotFoundError when no IterationNote was found.
func (_q *IterationNoteQuery) First(ctx context.Context) (*IterationNote, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{iterationnote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *IterationNoteQuery) FirstX(ctx context.Context) *IterationNote {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IterationNote ID from the query.
// Returns a *NotFoundError when no IterationNote ID was found.
func (_q *IterationNoteQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{iterationnote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IterationNoteQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IterationNote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IterationNote entity is found.
// Returns a *NotFoundError when no IterationNote entities are found.
func (_q *IterationNoteQuery) Only(ctx context.Context) (*IterationNote, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{iterationnote.Label}
	default:
		return nil, &NotSingularError{iterationnote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *IterationNoteQuery) OnlyX(ctx context.Context) *IterationNote {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IterationNote ID in the query.
// Returns a *NotSingularError when more than one IterationNote ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IterationNoteQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{iterationnote.Label}
	default:
		err = &NotSingularError{iterationnote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IterationNoteQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IterationNotes.
func (_q *IterationNoteQuery) All(ctx context.Context) ([]*IterationNote, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IterationNote, *IterationNoteQuery]()
	return withInterceptors[[]*IterationNote](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *IterationNoteQuery) AllX(ctx context.Context) []*IterationNote {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IterationNote IDs.
func (_q *IterationNoteQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(iterationnote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *IterationNoteQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *IterationNoteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*IterationNoteQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *IterationNoteQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *IterationNoteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *IterationNoteQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IterationNoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IterationNoteQuery) Clone() *IterationNoteQuery {
	if _q == nil {
		return nil
	}
	return &IterationNoteQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]iterationnote.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.IterationNote{}, _q.predicates...),
		withProject: _q.withProject.Clone(),
		withChange:  _q.withChange.Clone(),
		withEvent:   _q.withEvent.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IterationNoteQuery) WithProject(opts ...func(*ProjectQuery)) *IterationNoteQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithChange tells the query-builder to eager-load the nodes that are connected to
// the "change" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IterationNoteQuery) WithChange(opts ...func(*ChangeQuery)) *IterationNoteQuery {
	query := (&ChangeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChange = query
	return _q
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IterationNoteQuery) WithEvent(opts ...func(*EventQuery)) *IterationNoteQuery {
	query := (&EventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvent = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IterationNote.Query().
//		GroupBy(iterationnote.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IterationNoteQuery) GroupBy(field string, fields ...string) *IterationNoteGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IterationNoteGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = iterationnote.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//	}
//
//	client.IterationNote.Query().
//		Select(iterationnote.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *IterationNoteQuery) Select(fields ...string) *IterationNoteSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IterationNoteSelect{IterationNoteQuery: _q}
	sbuild.label = iterationnote.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IterationNoteSelect configured with the given aggregations.
func (_q *IterationNoteQuery) Aggregate(fns ...AggregateFunc) *IterationNoteSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *IterationNoteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !iterationnote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *IterationNoteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IterationNote, error) {
	var (
		nodes       = []*IterationNote{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProject != nil,
			_q.withChange != nil,
			_q.withEvent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IterationNote).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IterationNote{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *IterationNote, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChange; query != nil {
		if err := _q.loadChange(ctx, query, nodes, nil,
			func(n *IterationNote, e *Change) { n.Edges.Change = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvent; query != nil {
		if err := _q.loadEvent(ctx, query, nodes, nil,
			func(n *IterationNote, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *IterationNoteQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*IterationNote, init func(*IterationNote), assign func(*IterationNote, *Project)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*IterationNote)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *IterationNoteQuery) loadChange(ctx context.Context, query *ChangeQuery, nodes []*IterationNote, init func(*IterationNote), assign func(*IterationNote, *Change)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*IterationNote)
	for i := range nodes {
		fk := nodes[i].ChangeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(change.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "change_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *IterationNoteQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*IterationNote, init func(*IterationNote), assign func(*IterationNote, *Event)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*IterationNote)
	for i := range nodes {
		fk := nodes[i].EventID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "event_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *IterationNoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *IterationNoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(iterationnote.Table, iterationnote.Columns, sqlgraph.NewFieldSpec(iterationnote.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, iterationnote.FieldID)
		for i := range fields {
			if fields[i] != iterationnote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(iterationnote.FieldProjectID)
		}
		if _q.withChange != nil {
			_spec.Node.AddColumnOnce(iterationnote.FieldChangeID)
		}
		if _q.withEvent != nil {
			_spec.Node.AddColumnOnce(iterationnote.FieldEventID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *IterationNoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(iterationnote.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = iterationnote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IterationNoteGroupBy is the group-by builder for IterationNote entities.
type IterationNoteGroupBy struct {
	selector
	build *IterationNoteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IterationNoteGroupBy) Aggregate(fns ...AggregateFunc) *IterationNoteGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *IterationNoteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IterationNoteQuery, *IterationNoteGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *IterationNoteGroupBy) sqlScan(ctx context.Context, root *IterationNoteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IterationNoteSelect is the builder for selecting fields of IterationNote entities.
type IterationNoteSelect struct {
	*IterationNoteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IterationNoteSelect) Aggregate(fns ...AggregateFunc) *IterationNoteSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *IterationNoteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IterationNoteQuery, *IterationNoteSelect](ctx, _s.IterationNoteQuery, _s, _s.inters, v)
}

func (_s *IterationNoteSelect) sqlScan(ctx context.Context, root *IterationNoteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
