// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/change"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/event"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/iterationnote"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
)

// IterationNoteUpdate is the builder for updating IterationNote entities.
type IterationNoteUpdate struct {
	config
	hooks    []Hook
	mutation *IterationNoteMutation
}

// Where appends a list predicates to the IterationNoteUpdate builder.
func (_u *IterationNoteUpdate) Where(ps ...predicate.IterationNote) *IterationNoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IterationNoteUpdate) SetUpdatedAt(v string) *IterationNoteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableUpdatedAt(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *IterationNoteUpdate) SetProjectID(v string) *IterationNoteUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableProjectID(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetChangeID sets the "change_id" field.
func (_u *IterationNoteUpdate) SetChangeID(v string) *IterationNoteUpdate {
	_u.mutation.SetChangeID(v)
	return _u
}

// SetNillableChangeID sets the "change_id" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableChangeID(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetChangeID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *IterationNoteUpdate) SetEventID(v string) *IterationNoteUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableEventID(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// ClearEventID clears the value of the "event_id" field.
func (_u *IterationNoteUpdate) ClearEventID() *IterationNoteUpdate {
	_u.mutation.ClearEventID()
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *IterationNoteUpdate) SetFilePath(v string) *IterationNoteUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableFilePath(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// ClearFilePath clears the value of the "file_path" field.
func (_u *IterationNoteUpdate) ClearFilePath() *IterationNoteUpdate {
	_u.mutation.ClearFilePath()
	return _u
}

// SetLineFrom sets the "line_from" field.
func (_u *IterationNoteUpdate) SetLineFrom(v int) *IterationNoteUpdate {
	_u.mutation.ResetLineFrom()
	_u.mutation.SetLineFrom(v)
	return _u
}

// SetNillableLineFrom sets the "line_from" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableLineFrom(v *int) *IterationNoteUpdate {
	if v != nil {
		_u.SetLineFrom(*v)
	}
	return _u
}

// AddLineFrom adds value to the "line_from" field.
func (_u *IterationNoteUpdate) AddLineFrom(v int) *IterationNoteUpdate {
	_u.mutation.AddLineFrom(v)
	return _u
}

// ClearLineFrom clears the value of the "line_from" field.
func (_u *IterationNoteUpdate) ClearLineFrom() *IterationNoteUpdate {
	_u.mutation.ClearLineFrom()
	return _u
}

// SetLineTo sets the "line_to" field.
func (_u *IterationNoteUpdate) SetLineTo(v int) *IterationNoteUpdate {
	_u.mutation.ResetLineTo()
	_u.mutation.SetLineTo(v)
	return _u
}

// SetNillableLineTo sets the "line_to" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableLineTo(v *int) *IterationNoteUpdate {
	if v != nil {
		_u.SetLineTo(*v)
	}
	return _u
}

// AddLineTo adds value to the "line_to" field.
func (_u *IterationNoteUpdate) AddLineTo(v int) *IterationNoteUpdate {
	_u.mutation.AddLineTo(v)
	return _u
}

// ClearLineTo clears the value of the "line_to" field.
func (_u *IterationNoteUpdate) ClearLineTo() *IterationNoteUpdate {
	_u.mutation.ClearLineTo()
	return _u
}

// SetBody sets the "body" field.
func (_u *IterationNoteUpdate) SetBody(v string) *IterationNoteUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableBody(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IterationNoteUpdate) SetStatus(v string) *IterationNoteUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableStatus(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *IterationNoteUpdate) SetDeliveredAt(v string) *IterationNoteUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableDeliveredAt(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *IterationNoteUpdate) ClearDeliveredAt() *IterationNoteUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *IterationNoteUpdate) SetResolvedAt(v string) *IterationNoteUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *IterationNoteUpdate) SetNillableResolvedAt(v *string) *IterationNoteUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *IterationNoteUpdate) ClearResolvedAt() *IterationNoteUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *IterationNoteUpdate) SetProject(v *Project) *IterationNoteUpdate {
	return _u.SetProjectID(v.ID)
}

// SetChange sets the "change" edge to the Change entity.
func (_u *IterationNoteUpdate) SetChange(v *Change) *IterationNoteUpdate {
	return _u.SetChangeID(v.ID)
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *IterationNoteUpdate) SetEvent(v *Event) *IterationNoteUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the IterationNoteMutation object of the builder.
func (_u *IterationNoteUpdate) Mutation() *IterationNoteMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *IterationNoteUpdate) ClearProject() *IterationNoteUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearChange clears the "change" edge to the Change entity.
func (_u *IterationNoteUpdate) ClearChange() *IterationNoteUpdate {
	_u.mutation.ClearChange()
	return _u
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *IterationNoteUpdate) ClearEvent() *IterationNoteUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IterationNoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IterationNoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IterationNoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IterationNoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IterationNoteUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IterationNote.project"`)
	}
	if _u.mutation.ChangeCleared() && len(_u.mutation.ChangeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IterationNote.change"`)
	}
	return nil
}

func (_u *IterationNoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(iterationnote.Table, iterationnote.Columns, sqlgraph.NewFieldSpec(iterationnote.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(iterationnote.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(iterationnote.FieldFilePath, field.TypeString, value)
	}
	if _u.mutation.FilePathCleared() {
		_spec.ClearField(iterationnote.FieldFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.LineFrom(); ok {
		_spec.SetField(iterationnote.FieldLineFrom, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineFrom(); ok {
		_spec.AddField(iterationnote.FieldLineFrom, field.TypeInt, value)
	}
	if _u.mutation.LineFromCleared() {
		_spec.ClearField(iterationnote.FieldLineFrom, field.TypeInt)
	}
	if value, ok := _u.mutation.LineTo(); ok {
		_spec.SetField(iterationnote.FieldLineTo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineTo(); ok {
		_spec.AddField(iterationnote.FieldLineTo, field.TypeInt, value)
	}
	if _u.mutation.LineToCleared() {
		_spec.ClearField(iterationnote.FieldLineTo, field.TypeInt)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(iterationnote.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(iterationnote.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(iterationnote.FieldDeliveredAt, field.TypeString, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(iterationnote.FieldDeliveredAt, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(iterationnote.FieldResolvedAt, field.TypeString, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(iterationnote.FieldResolvedAt, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ProjectTable,
			Columns: []string{iterationnote.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ProjectTable,
			Columns: []string{iterationnote.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ChangeTable,
			Columns: []string{iterationnote.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ChangeTable,
			Columns: []string{iterationnote.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.EventTable,
			Columns: []string{iterationnote.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.EventTable,
			Columns: []string{iterationnote.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{iterationnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IterationNoteUpdateOne is the builder for updating a single IterationNote entity.
type IterationNoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IterationNoteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IterationNoteUpdateOne) SetUpdatedAt(v string) *IterationNoteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableUpdatedAt(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *IterationNoteUpdateOne) SetProjectID(v string) *IterationNoteUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableProjectID(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetChangeID sets the "change_id" field.
func (_u *IterationNoteUpdateOne) SetChangeID(v string) *IterationNoteUpdateOne {
	_u.mutation.SetChangeID(v)
	return _u
}

// SetNillableChangeID sets the "change_id" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableChangeID(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetChangeID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *IterationNoteUpdateOne) SetEventID(v string) *IterationNoteUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableEventID(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// ClearEventID clears the value of the "event_id" field.
func (_u *IterationNoteUpdateOne) ClearEventID() *IterationNoteUpdateOne {
	_u.mutation.ClearEventID()
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *IterationNoteUpdateOne) SetFilePath(v string) *IterationNoteUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableFilePath(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// ClearFilePath clears the value of the "file_path" field.
func (_u *IterationNoteUpdateOne) ClearFilePath() *IterationNoteUpdateOne {
	_u.mutation.ClearFilePath()
	return _u
}

// SetLineFrom sets the "line_from" field.
func (_u *IterationNoteUpdateOne) SetLineFrom(v int) *IterationNoteUpdateOne {
	_u.mutation.ResetLineFrom()
	_u.mutation.SetLineFrom(v)
	return _u
}

// SetNillableLineFrom sets the "line_from" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableLineFrom(v *int) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetLineFrom(*v)
	}
	return _u
}

// AddLineFrom adds value to the "line_from" field.
func (_u *IterationNoteUpdateOne) AddLineFrom(v int) *IterationNoteUpdateOne {
	_u.mutation.AddLineFrom(v)
	return _u
}

// ClearLineFrom clears the value of the "line_from" field.
func (_u *IterationNoteUpdateOne) ClearLineFrom() *IterationNoteUpdateOne {
	_u.mutation.ClearLineFrom()
	return _u
}

// SetLineTo sets the "line_to" field.
func (_u *IterationNoteUpdateOne) SetLineTo(v int) *IterationNoteUpdateOne {
	_u.mutation.ResetLineTo()
	_u.mutation.SetLineTo(v)
	return _u
}

// SetNillableLineTo sets the "line_to" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableLineTo(v *int) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetLineTo(*v)
	}
	return _u
}

// AddLineTo adds value to the "line_to" field.
func (_u *IterationNoteUpdateOne) AddLineTo(v int) *IterationNoteUpdateOne {
	_u.mutation.AddLineTo(v)
	return _u
}

// ClearLineTo clears the value of the "line_to" field.
func (_u *IterationNoteUpdateOne) ClearLineTo() *IterationNoteUpdateOne {
	_u.mutation.ClearLineTo()
	return _u
}

// SetBody sets the "body" field.
func (_u *IterationNoteUpdateOne) SetBody(v string) *IterationNoteUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableBody(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IterationNoteUpdateOne) SetStatus(v string) *IterationNoteUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableStatus(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *IterationNoteUpdateOne) SetDeliveredAt(v string) *IterationNoteUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableDeliveredAt(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *IterationNoteUpdateOne) ClearDeliveredAt() *IterationNoteUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *IterationNoteUpdateOne) SetResolvedAt(v string) *IterationNoteUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *IterationNoteUpdateOne) SetNillableResolvedAt(v *string) *IterationNoteUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *IterationNoteUpdateOne) ClearResolvedAt() *IterationNoteUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *IterationNoteUpdateOne) SetProject(v *Project) *IterationNoteUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetChange sets the "change" edge to the Change entity.
func (_u *IterationNoteUpdateOne) SetChange(v *Change) *IterationNoteUpdateOne {
	return _u.SetChangeID(v.ID)
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *IterationNoteUpdateOne) SetEvent(v *Event) *IterationNoteUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the IterationNoteMutation object of the builder.
func (_u *IterationNoteUpdateOne) Mutation() *IterationNoteMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *IterationNoteUpdateOne) ClearProject() *IterationNoteUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearChange clears the "change" edge to the Change entity.
func (_u *IterationNoteUpdateOne) ClearChange() *IterationNoteUpdateOne {
	_u.mutation.ClearChange()
	return _u
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *IterationNoteUpdateOne) ClearEvent() *IterationNoteUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the IterationNoteUpdate builder.
func (_u *IterationNoteUpdateOne) Where(ps ...predicate.IterationNote) *IterationNoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IterationNoteUpdateOne) Select(field string, fields ...string) *IterationNoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IterationNote entity.
func (_u *IterationNoteUpdateOne) Save(ctx context.Context) (*IterationNote, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IterationNoteUpdateOne) SaveX(ctx context.Context) *IterationNote {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IterationNoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IterationNoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IterationNoteUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IterationNote.project"`)
	}
	if _u.mutation.ChangeCleared() && len(_u.mutation.ChangeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IterationNote.change"`)
	}
	return nil
}

func (_u *IterationNoteUpdateOne) sqlSave(ctx context.Context) (_node *IterationNote, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(iterationnote.Table, iterationnote.Columns, sqlgraph.NewFieldSpec(iterationnote.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IterationNote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, iterationnote.FieldID)
		for _, f := range fields {
			if !iterationnote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != iterationnote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(iterationnote.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(iterationnote.FieldFilePath, field.TypeString, value)
	}
	if _u.mutation.FilePathCleared() {
		_spec.ClearField(iterationnote.FieldFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.LineFrom(); ok {
		_spec.SetField(iterationnote.FieldLineFrom, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineFrom(); ok {
		_spec.AddField(iterationnote.FieldLineFrom, field.TypeInt, value)
	}
	if _u.mutation.LineFromCleared() {
		_spec.ClearField(iterationnote.FieldLineFrom, field.TypeInt)
	}
	if value, ok := _u.mutation.LineTo(); ok {
		_spec.SetField(iterationnote.FieldLineTo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineTo(); ok {
		_spec.AddField(iterationnote.FieldLineTo, field.TypeInt, value)
	}
	if _u.mutation.LineToCleared() {
		_spec.ClearField(iterationnote.FieldLineTo, field.TypeInt)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(iterationnote.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(iterationnote.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(iterationnote.FieldDeliveredAt, field.TypeString, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(iterationnote.FieldDeliveredAt, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(iterationnote.FieldResolvedAt, field.TypeString, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(iterationnote.FieldResolvedAt, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ProjectTable,
			Columns: []string{iterationnote.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ProjectTable,
			Columns: []string{iterationnote.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ChangeTable,
			Columns: []string{iterationnote.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.ChangeTable,
			Columns: []string{iterationnote.ChangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.EventTable,
			Columns: []string{iterationnote.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   iterationnote.EventTable,
			Columns: []string{iterationnote.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IterationNote{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{iterationnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
