// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/projectpath"
)

// ProjectPathUpdate is the builder for updating ProjectPath entities.
type ProjectPathUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectPathMutation
}

// Where appends a list predicates to the ProjectPathUpdate builder.
func (_u *ProjectPathUpdate) Where(ps ...predicate.ProjectPath) *ProjectPathUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectPathUpdate) SetUpdatedAt(v string) *ProjectPathUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProjectPathUpdate) SetNillableUpdatedAt(v *string) *ProjectPathUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectPathUpdate) SetProjectID(v string) *ProjectPathUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectPathUpdate) SetNillableProjectID(v *string) *ProjectPathUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetMachineID sets the "machine_id" field.
func (_u *ProjectPathUpdate) SetMachineID(v string) *ProjectPathUpdate {
	_u.mutation.SetMachineID(v)
	return _u
}

// SetNillableMachineID sets the "machine_id" field if the given value is not nil.
func (_u *ProjectPathUpdate) SetNillableMachineID(v *string) *ProjectPathUpdate {
	if v != nil {
		_u.SetMachineID(*v)
	}
	return _u
}

// SetRootPath sets the "root_path" field.
func (_u *ProjectPathUpdate) SetRootPath(v string) *ProjectPathUpdate {
	_u.mutation.SetRootPath(v)
	return _u
}

// SetNillableRootPath sets the "root_path" field if the given value is not nil.
func (_u *ProjectPathUpdate) SetNillableRootPath(v *string) *ProjectPathUpdate {
	if v != nil {
		_u.SetRootPath(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProjectPathUpdate) SetStatus(v string) *ProjectPathUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProjectPathUpdate) SetNillableStatus(v *string) *ProjectPathUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ProjectPathUpdate) SetLastSeenAt(v string) *ProjectPathUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ProjectPathUpdate) SetNillableLastSeenAt(v *string) *ProjectPathUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectPathUpdate) SetProject(v *Project) *ProjectPathUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectPathMutation object of the builder.
func (_u *ProjectPathUpdate) Mutation() *ProjectPathMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectPathUpdate) ClearProject() *ProjectPathUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectPathUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectPathUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectPathUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectPathUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectPathUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectPath.project"`)
	}
	return nil
}

func (_u *ProjectPathUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectpath.Table, projectpath.Columns, sqlgraph.NewFieldSpec(projectpath.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projectpath.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.MachineID(); ok {
		_spec.SetField(projectpath.FieldMachineID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootPath(); ok {
		_spec.SetField(projectpath.FieldRootPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(projectpath.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(projectpath.FieldLastSeenAt, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectpath.ProjectTable,
			Columns: []string{projectpath.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectpath.ProjectTable,
			Columns: []string{projectpath.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectpath.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectPathUpdateOne is the builder for updating a single ProjectPath entity.
type ProjectPathUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectPathMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectPathUpdateOne) SetUpdatedAt(v string) *ProjectPathUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProjectPathUpdateOne) SetNillableUpdatedAt(v *string) *ProjectPathUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectPathUpdateOne) SetProjectID(v string) *ProjectPathUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectPathUpdateOne) SetNillableProjectID(v *string) *ProjectPathUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetMachineID sets the "machine_id" field.
func (_u *ProjectPathUpdateOne) SetMachineID(v string) *ProjectPathUpdateOne {
	_u.mutation.SetMachineID(v)
	return _u
}

// SetNillableMachineID sets the "machine_id" field if the given value is not nil.
func (_u *ProjectPathUpdateOne) SetNillableMachineID(v *string) *ProjectPathUpdateOne {
	if v != nil {
		_u.SetMachineID(*v)
	}
	return _u
}

// SetRootPath sets the "root_path" field.
func (_u *ProjectPathUpdateOne) SetRootPath(v string) *ProjectPathUpdateOne {
	_u.mutation.SetRootPath(v)
	return _u
}

// SetNillableRootPath sets the "root_path" field if the given value is not nil.
func (_u *ProjectPathUpdateOne) SetNillableRootPath(v *string) *ProjectPathUpdateOne {
	if v != nil {
		_u.SetRootPath(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProjectPathUpdateOne) SetStatus(v string) *ProjectPathUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProjectPathUpdateOne) SetNillableStatus(v *string) *ProjectPathUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ProjectPathUpdateOne) SetLastSeenAt(v string) *ProjectPathUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ProjectPathUpdateOne) SetNillableLastSeenAt(v *string) *ProjectPathUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectPathUpdateOne) SetProject(v *Project) *ProjectPathUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectPathMutation object of the builder.
func (_u *ProjectPathUpdateOne) Mutation() *ProjectPathMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectPathUpdateOne) ClearProject() *ProjectPathUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ProjectPathUpdate builder.
func (_u *ProjectPathUpdateOne) Where(ps ...predicate.ProjectPath) *ProjectPathUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectPathUpdateOne) Select(field string, fields ...string) *ProjectPathUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectPath entity.
func (_u *ProjectPathUpdateOne) Save(ctx context.Context) (*ProjectPath, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectPathUpdateOne) SaveX(ctx context.Context) *ProjectPath {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectPathUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectPathUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectPathUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectPath.project"`)
	}
	return nil
}

func (_u *ProjectPathUpdateOne) sqlSave(ctx context.Context) (_node *ProjectPath, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectpath.Table, projectpath.Columns, sqlgraph.NewFieldSpec(projectpath.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectPath.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectpath.FieldID)
		for _, f := range fields {
			if !projectpath.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectpath.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projectpath.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.MachineID(); ok {
		_spec.SetField(projectpath.FieldMachineID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootPath(); ok {
		_spec.SetField(projectpath.FieldRootPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(projectpath.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(projectpath.FieldLastSeenAt, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectpath.ProjectTable,
			Columns: []string{projectpath.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectpath.ProjectTable,
			Columns: []string{projectpath.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectPath{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectpath.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
