// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/contentobject"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/record"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
)

// RecordVersionQuery is the builder for querying RecordVersion entities.
type RecordVersionQuery struct {
	config
	ctx               *QueryContext
	order             []recordversion.OrderOption
	inters            []Interceptor
	predicates        []predicate.RecordVersion
	withProject       *ProjectQuery
	withRecord        *RecordQuery
	withContentObject *ContentObjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecordVersionQuery builder.
func (_q *RecordVersionQuery) Where(ps ...predicate.RecordVersion) *RecordVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RecordVersionQuery) Limit(limit int) *RecordVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RecordVersionQuery) Offset(offset int) *RecordVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RecordVersionQuery) Unique(unique bool) *RecordVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RecordVersionQuery) Order(o ...recordversion.OrderOption) *RecordVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *RecordVersionQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversion.Table, recordversion.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversion.ProjectTable, recordversion.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRecord chains the current query on the "record" edge.
func (_q *RecordVersionQuery) QueryRecord() *RecordQuery {
	query := (&RecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversion.Table, recordversion.FieldID, selector),
			sqlgraph.To(record.Table, record.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversion.RecordTable, recordversion.RecordColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContentObject chains the current query on the "content_object" edge.
func (_q *RecordVersionQuery) QueryContentObject() *ContentObjectQuery {
	query := (&ContentObjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversion.Table, recordversion.FieldID, selector),
			sqlgraph.To(contentobject.Table, contentobject.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversion.ContentObjectTable, recordversion.ContentObjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RecordVersion entity from the query.
// Returns a *NotFoundError when no RecordVersion was found.
func (_q *RecordVersionQuery) First(ctx context.Context) (*RecordVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recordversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RecordVersionQuery) FirstX(ctx context.Context) *RecordVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecordVersion ID from the query.
// Returns a *NotFoundError when no RecordVersion ID was found.
func (_q *RecordVersionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recordversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RecordVersionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecordVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecordVersion entity is found.
// Returns a *NotFoundError when no RecordVersion entities are found.
func (_q *RecordVersionQuery) Only(ctx context.Context) (*RecordVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recordversion.Label}
	default:
		return nil, &NotSingularError{recordversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RecordVersionQuery) OnlyX(ctx context.Context) *RecordVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecordVersion ID in the query.
// Returns a *NotSingularError when more than one RecordVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RecordVersionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recordversion.Label}
	default:
		err = &NotSingularError{recordversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RecordVersionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecordVersions.
func (_q *RecordVersionQuery) All(ctx context.Context) ([]*RecordVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RecordVersion, *RecordVersionQuery]()
	return withInterceptors[[]*RecordVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RecordVersionQuery) AllX(ctx context.Context) []*RecordVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecordVersion IDs.
func (_q *RecordVersionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(recordversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RecordVersionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RecordVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RecordVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RecordVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RecordVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RecordVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecordVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RecordVersionQuery) Clone() *RecordVersionQuery {
	if _q == nil {
		return nil
	}
	return &RecordVersionQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]recordversion.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.RecordVersion{}, _q.predicates...),
		withProject:       _q.withProject.Clone(),
		withRecord:        _q.withRecord.Clone(),
		withContentObject: _q.withContentObject.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecordVersionQuery) WithProject(opts ...func(*ProjectQuery)) *RecordVersionQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithRecord tells the query-builder to eager-load the nodes that are connected to
// the "record" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecordVersionQuery) WithRecord(opts ...func(*RecordQuery)) *RecordVersionQuery {
	query := (&RecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecord = query
	return _q
}

// WithContentObject tells the query-builder to eager-load the nodes that are connected to
// the "content_object" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecordVersionQuery) WithContentObject(opts ...func(*ContentObjectQuery)) *RecordVersionQuery {
	query := (&ContentObjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContentObject = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecordVersion.Query().
//		GroupBy(recordversion.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RecordVersionQuery) GroupBy(field string, fields ...string) *RecordVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RecordVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = recordversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//	}
//
//	client.RecordVersion.Query().
//		Select(recordversion.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RecordVersionQuery) Select(fields ...string) *RecordVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RecordVersionSelect{RecordVersionQuery: _q}
	sbuild.label = recordversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RecordVersionSelect configured with the given aggregations.
func (_q *RecordVersionQuery) Aggregate(fns ...AggregateFunc) *RecordVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RecordVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !recordversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RecordVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecordVersion, error) {
	var (
		nodes       = []*RecordVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProject != nil,
			_q.withRecord != nil,
			_q.withContentObject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecordVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecordVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *RecordVersion, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRecord; query != nil {
		if err := _q.loadRecord(ctx, query, nodes, nil,
			func(n *RecordVersion, e *Record) { n.Edges.Record = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withContentObject; query != nil {
		if err := _q.loadContentObject(ctx, query, nodes, nil,
			func(n *RecordVersion, e *ContentObject) { n.Edges.ContentObject = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RecordVersionQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*RecordVersion, init func(*RecordVersion), assign func(*RecordVersion, *Project)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RecordVersion)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RecordVersionQuery) loadRecord(ctx context.Context, query *RecordQuery, nodes []*RecordVersion, init func(*RecordVersion), assign func(*RecordVersion, *Record)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RecordVersion)
	for i := range nodes {
		fk := nodes[i].RecordID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(record.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "record_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RecordVersionQuery) loadContentObject(ctx context.Context, query *ContentObjectQuery, nodes []*RecordVersion, init func(*RecordVersion), assign func(*RecordVersion, *ContentObject)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RecordVersion)
	for i := range nodes {
		fk := nodes[i].ContentObjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contentobject.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "content_object_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RecordVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RecordVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(recordversion.Table, recordversion.Columns, sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recordversion.FieldID)
		for i := range fields {
			if fields[i] != recordversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(recordversion.FieldProjectID)
		}
		if _q.withRecord != nil {
			_spec.Node.AddColumnOnce(recordversion.FieldRecordID)
		}
		if _q.withContentObject != nil {
			_spec.Node.AddColumnOnce(recordversion.FieldContentObjectID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RecordVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(recordversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = recordversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecordVersionGroupBy is the group-by builder for RecordVersion entities.
type RecordVersionGroupBy struct {
	selector
	build *RecordVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RecordVersionGroupBy) Aggregate(fns ...AggregateFunc) *RecordVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RecordVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecordVersionQuery, *RecordVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RecordVersionGroupBy) sqlScan(ctx context.Context, root *RecordVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RecordVersionSelect is the builder for selecting fields of RecordVersion entities.
type RecordVersionSelect struct {
	*RecordVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RecordVersionSelect) Aggregate(fns ...AggregateFunc) *RecordVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RecordVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecordVersionQuery, *RecordVersionSelect](ctx, _s.RecordVersionQuery, _s, _s.inters, v)
}

func (_s *RecordVersionSelect) sqlScan(ctx context.Context, root *RecordVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
