// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/contentobject"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/record"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
)

// RecordVersionCreate is the builder for creating a RecordVersion entity.
type RecordVersionCreate struct {
	config
	mutation *RecordVersionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecordVersionCreate) SetCreatedAt(v string) *RecordVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecordVersionCreate) SetNillableCreatedAt(v *string) *RecordVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RecordVersionCreate) SetUpdatedAt(v string) *RecordVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RecordVersionCreate) SetNillableUpdatedAt(v *string) *RecordVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *RecordVersionCreate) SetProjectID(v string) *RecordVersionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetRecordID sets the "record_id" field.
func (_c *RecordVersionCreate) SetRecordID(v string) *RecordVersionCreate {
	_c.mutation.SetRecordID(v)
	return _c
}

// SetContentObjectID sets the "content_object_id" field.
func (_c *RecordVersionCreate) SetContentObjectID(v string) *RecordVersionCreate {
	_c.mutation.SetContentObjectID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RecordVersionCreate) SetStatus(v string) *RecordVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *RecordVersionCreate) SetKind(v string) *RecordVersionCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *RecordVersionCreate) SetNillableKind(v *string) *RecordVersionCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetDocStatus sets the "doc_status" field.
func (_c *RecordVersionCreate) SetDocStatus(v string) *RecordVersionCreate {
	_c.mutation.SetDocStatus(v)
	return _c
}

// SetNillableDocStatus sets the "doc_status" field if the given value is not nil.
func (_c *RecordVersionCreate) SetNillableDocStatus(v *string) *RecordVersionCreate {
	if v != nil {
		_c.SetDocStatus(*v)
	}
	return _c
}

// SetFrozenAt sets the "frozen_at" field.
func (_c *RecordVersionCreate) SetFrozenAt(v string) *RecordVersionCreate {
	_c.mutation.SetFrozenAt(v)
	return _c
}

// SetNillableFrozenAt sets the "frozen_at" field if the given value is not nil.
func (_c *RecordVersionCreate) SetNillableFrozenAt(v *string) *RecordVersionCreate {
	if v != nil {
		_c.SetFrozenAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RecordVersionCreate) SetID(v string) *RecordVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecordVersionCreate) SetNillableID(v *string) *RecordVersionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *RecordVersionCreate) SetProject(v *Project) *RecordVersionCreate {
	return _c.SetProjectID(v.ID)
}

// SetRecord sets the "record" edge to the Record entity.
func (_c *RecordVersionCreate) SetRecord(v *Record) *RecordVersionCreate {
	return _c.SetRecordID(v.ID)
}

// SetContentObject sets the "content_object" edge to the ContentObject entity.
func (_c *RecordVersionCreate) SetContentObject(v *ContentObject) *RecordVersionCreate {
	return _c.SetContentObjectID(v.ID)
}

// Mutation returns the RecordVersionMutation object of the builder.
func (_c *RecordVersionCreate) Mutation() *RecordVersionMutation {
	return _c.mutation
}

// Save creates the RecordVersion in the database.
func (_c *RecordVersionCreate) Save(ctx context.Context) (*RecordVersion, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecordVersionCreate) SaveX(ctx context.Context) *RecordVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecordVersionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if recordversion.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized recordversion.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := recordversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if recordversion.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized recordversion.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := recordversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if recordversion.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized recordversion.DefaultID (forgotten import ent/runtime?)")
		}
		v := recordversion.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecordVersionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecordVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecordVersion.updated_at"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "RecordVersion.project_id"`)}
	}
	if _, ok := _c.mutation.RecordID(); !ok {
		return &ValidationError{Name: "record_id", err: errors.New(`ent: missing required field "RecordVersion.record_id"`)}
	}
	if _, ok := _c.mutation.ContentObjectID(); !ok {
		return &ValidationError{Name: "content_object_id", err: errors.New(`ent: missing required field "RecordVersion.content_object_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RecordVersion.status"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "RecordVersion.project"`)}
	}
	if len(_c.mutation.RecordIDs()) == 0 {
		return &ValidationError{Name: "record", err: errors.New(`ent: missing required edge "RecordVersion.record"`)}
	}
	if len(_c.mutation.ContentObjectIDs()) == 0 {
		return &ValidationError{Name: "content_object", err: errors.New(`ent: missing required edge "RecordVersion.content_object"`)}
	}
	return nil
}

func (_c *RecordVersionCreate) sqlSave(ctx context.Context) (*RecordVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RecordVersion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecordVersionCreate) createSpec() (*RecordVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &RecordVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recordversion.Table, sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recordversion.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(recordversion.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(recordversion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(recordversion.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.DocStatus(); ok {
		_spec.SetField(recordversion.FieldDocStatus, field.TypeString, value)
		_node.DocStatus = value
	}
	if value, ok := _c.mutation.FrozenAt(); ok {
		_spec.SetField(recordversion.FieldFrozenAt, field.TypeString, value)
		_node.FrozenAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversion.ProjectTable,
			Columns: []string{recordversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversion.RecordTable,
			Columns: []string{recordversion.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecordID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContentObjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversion.ContentObjectTable,
			Columns: []string{recordversion.ContentObjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentobject.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContentObjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecordVersionCreateBulk is the builder for creating many RecordVersion entities in bulk.
type RecordVersionCreateBulk struct {
	config
	err      error
	builders []*RecordVersionCreate
}

// Save creates the RecordVersion entities in the database.
func (_c *RecordVersionCreateBulk) Save(ctx context.Context) ([]*RecordVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecordVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecordVersionCreateBulk) SaveX(ctx context.Context) []*RecordVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
