// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/contentobject"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/record"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
)

// RecordVersion is the model entity for the RecordVersion schema.
type RecordVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt string `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// RecordID holds the value of the "record_id" field.
	RecordID string `json:"record_id,omitempty"`
	// ContentObjectID holds the value of the "content_object_id" field.
	ContentObjectID string `json:"content_object_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// DocStatus holds the value of the "doc_status" field.
	DocStatus string `json:"doc_status,omitempty"`
	// FrozenAt holds the value of the "frozen_at" field.
	FrozenAt string `json:"frozen_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecordVersionQuery when eager-loading is set.
	Edges        RecordVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RecordVersionEdges holds the relations/edges for other nodes in the graph.
type RecordVersionEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Record holds the value of the record edge.
	Record *Record `json:"record,omitempty"`
	// ContentObject holds the value of the content_object edge.
	ContentObject *ContentObject `json:"content_object,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordVersionEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// RecordOrErr returns the Record value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordVersionEdges) RecordOrErr() (*Record, error) {
	if e.Record != nil {
		return e.Record, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: record.Label}
	}
	return nil, &NotLoadedError{edge: "record"}
}

// ContentObjectOrErr returns the ContentObject value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordVersionEdges) ContentObjectOrErr() (*ContentObject, error) {
	if e.ContentObject != nil {
		return e.ContentObject, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: contentobject.Label}
	}
	return nil, &NotLoadedError{edge: "content_object"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecordVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recordversion.FieldID, recordversion.FieldCreatedAt, recordversion.FieldUpdatedAt, recordversion.FieldProjectID, recordversion.FieldRecordID, recordversion.FieldContentObjectID, recordversion.FieldStatus, recordversion.FieldKind, recordversion.FieldDocStatus, recordversion.FieldFrozenAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecordVersion fields.
func (_m *RecordVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recordversion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case recordversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case recordversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.String
			}
		case recordversion.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		case recordversion.FieldRecordID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field record_id", values[i])
			} else if value.Valid {
				_m.RecordID = value.String
			}
		case recordversion.FieldContentObjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_object_id", values[i])
			} else if value.Valid {
				_m.ContentObjectID = value.String
			}
		case recordversion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case recordversion.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case recordversion.FieldDocStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field doc_status", values[i])
			} else if value.Valid {
				_m.DocStatus = value.String
			}
		case recordversion.FieldFrozenAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_at", values[i])
			} else if value.Valid {
				_m.FrozenAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecordVersion.
// This includes values selected through modifiers, order, etc.
func (_m *RecordVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the RecordVersion entity.
func (_m *RecordVersion) QueryProject() *ProjectQuery {
	return NewRecordVersionClient(_m.config).QueryProject(_m)
}

// QueryRecord queries the "record" edge of the RecordVersion entity.
func (_m *RecordVersion) QueryRecord() *RecordQuery {
	return NewRecordVersionClient(_m.config).QueryRecord(_m)
}

// QueryContentObject queries the "content_object" edge of the RecordVersion entity.
func (_m *RecordVersion) QueryContentObject() *ContentObjectQuery {
	return NewRecordVersionClient(_m.config).QueryContentObject(_m)
}

// Update returns a builder for updating this RecordVersion.
// Note that you need to call RecordVersion.Unwrap() before calling this method if this RecordVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecordVersion) Update() *RecordVersionUpdateOne {
	return NewRecordVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecordVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecordVersion) Unwrap() *RecordVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecordVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecordVersion) String() string {
	var builder strings.Builder
	builder.WriteString("RecordVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("record_id=")
	builder.WriteString(_m.RecordID)
	builder.WriteString(", ")
	builder.WriteString("content_object_id=")
	builder.WriteString(_m.ContentObjectID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("doc_status=")
	builder.WriteString(_m.DocStatus)
	builder.WriteString(", ")
	builder.WriteString("frozen_at=")
	builder.WriteString(_m.FrozenAt)
	builder.WriteByte(')')
	return builder.String()
}

// RecordVersions is a parsable slice of RecordVersion.
type RecordVersions []*RecordVersion
