// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversionref"
)

// RecordVersionRefCreate is the builder for creating a RecordVersionRef entity.
type RecordVersionRefCreate struct {
	config
	mutation *RecordVersionRefMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecordVersionRefCreate) SetCreatedAt(v string) *RecordVersionRefCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecordVersionRefCreate) SetNillableCreatedAt(v *string) *RecordVersionRefCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RecordVersionRefCreate) SetUpdatedAt(v string) *RecordVersionRefCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RecordVersionRefCreate) SetNillableUpdatedAt(v *string) *RecordVersionRefCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *RecordVersionRefCreate) SetProjectID(v string) *RecordVersionRefCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetRecordVersionID sets the "record_version_id" field.
func (_c *RecordVersionRefCreate) SetRecordVersionID(v string) *RecordVersionRefCreate {
	_c.mutation.SetRecordVersionID(v)
	return _c
}

// SetRelation sets the "relation" field.
func (_c *RecordVersionRefCreate) SetRelation(v string) *RecordVersionRefCreate {
	_c.mutation.SetRelation(v)
	return _c
}

// SetTargetSlug sets the "target_slug" field.
func (_c *RecordVersionRefCreate) SetTargetSlug(v string) *RecordVersionRefCreate {
	_c.mutation.SetTargetSlug(v)
	return _c
}

// SetTargetOwningRoot sets the "target_owning_root" field.
func (_c *RecordVersionRefCreate) SetTargetOwningRoot(v string) *RecordVersionRefCreate {
	_c.mutation.SetTargetOwningRoot(v)
	return _c
}

// SetNillableTargetOwningRoot sets the "target_owning_root" field if the given value is not nil.
func (_c *RecordVersionRefCreate) SetNillableTargetOwningRoot(v *string) *RecordVersionRefCreate {
	if v != nil {
		_c.SetTargetOwningRoot(*v)
	}
	return _c
}

// SetDangling sets the "dangling" field.
func (_c *RecordVersionRefCreate) SetDangling(v int8) *RecordVersionRefCreate {
	_c.mutation.SetDangling(v)
	return _c
}

// SetNillableDangling sets the "dangling" field if the given value is not nil.
func (_c *RecordVersionRefCreate) SetNillableDangling(v *int8) *RecordVersionRefCreate {
	if v != nil {
		_c.SetDangling(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RecordVersionRefCreate) SetID(v string) *RecordVersionRefCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecordVersionRefCreate) SetNillableID(v *string) *RecordVersionRefCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *RecordVersionRefCreate) SetProject(v *Project) *RecordVersionRefCreate {
	return _c.SetProjectID(v.ID)
}

// SetRecordVersion sets the "record_version" edge to the RecordVersion entity.
func (_c *RecordVersionRefCreate) SetRecordVersion(v *RecordVersion) *RecordVersionRefCreate {
	return _c.SetRecordVersionID(v.ID)
}

// Mutation returns the RecordVersionRefMutation object of the builder.
func (_c *RecordVersionRefCreate) Mutation() *RecordVersionRefMutation {
	return _c.mutation
}

// Save creates the RecordVersionRef in the database.
func (_c *RecordVersionRefCreate) Save(ctx context.Context) (*RecordVersionRef, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecordVersionRefCreate) SaveX(ctx context.Context) *RecordVersionRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordVersionRefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordVersionRefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecordVersionRefCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if recordversionref.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized recordversionref.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := recordversionref.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if recordversionref.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized recordversionref.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := recordversionref.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Dangling(); !ok {
		v := recordversionref.DefaultDangling
		_c.mutation.SetDangling(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if recordversionref.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized recordversionref.DefaultID (forgotten import ent/runtime?)")
		}
		v := recordversionref.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecordVersionRefCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecordVersionRef.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecordVersionRef.updated_at"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "RecordVersionRef.project_id"`)}
	}
	if _, ok := _c.mutation.RecordVersionID(); !ok {
		return &ValidationError{Name: "record_version_id", err: errors.New(`ent: missing required field "RecordVersionRef.record_version_id"`)}
	}
	if _, ok := _c.mutation.Relation(); !ok {
		return &ValidationError{Name: "relation", err: errors.New(`ent: missing required field "RecordVersionRef.relation"`)}
	}
	if _, ok := _c.mutation.TargetSlug(); !ok {
		return &ValidationError{Name: "target_slug", err: errors.New(`ent: missing required field "RecordVersionRef.target_slug"`)}
	}
	if _, ok := _c.mutation.Dangling(); !ok {
		return &ValidationError{Name: "dangling", err: errors.New(`ent: missing required field "RecordVersionRef.dangling"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "RecordVersionRef.project"`)}
	}
	if len(_c.mutation.RecordVersionIDs()) == 0 {
		return &ValidationError{Name: "record_version", err: errors.New(`ent: missing required edge "RecordVersionRef.record_version"`)}
	}
	return nil
}

func (_c *RecordVersionRefCreate) sqlSave(ctx context.Context) (*RecordVersionRef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RecordVersionRef.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecordVersionRefCreate) createSpec() (*RecordVersionRef, *sqlgraph.CreateSpec) {
	var (
		_node = &RecordVersionRef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recordversionref.Table, sqlgraph.NewFieldSpec(recordversionref.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recordversionref.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(recordversionref.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Relation(); ok {
		_spec.SetField(recordversionref.FieldRelation, field.TypeString, value)
		_node.Relation = value
	}
	if value, ok := _c.mutation.TargetSlug(); ok {
		_spec.SetField(recordversionref.FieldTargetSlug, field.TypeString, value)
		_node.TargetSlug = value
	}
	if value, ok := _c.mutation.TargetOwningRoot(); ok {
		_spec.SetField(recordversionref.FieldTargetOwningRoot, field.TypeString, value)
		_node.TargetOwningRoot = value
	}
	if value, ok := _c.mutation.Dangling(); ok {
		_spec.SetField(recordversionref.FieldDangling, field.TypeInt8, value)
		_node.Dangling = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.ProjectTable,
			Columns: []string{recordversionref.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecordVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.RecordVersionTable,
			Columns: []string{recordversionref.RecordVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecordVersionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecordVersionRefCreateBulk is the builder for creating many RecordVersionRef entities in bulk.
type RecordVersionRefCreateBulk struct {
	config
	err      error
	builders []*RecordVersionRefCreate
}

// Save creates the RecordVersionRef entities in the database.
func (_c *RecordVersionRefCreateBulk) Save(ctx context.Context) ([]*RecordVersionRef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecordVersionRef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordVersionRefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecordVersionRefCreateBulk) SaveX(ctx context.Context) []*RecordVersionRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordVersionRefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordVersionRefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
