// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversionref"
)

// RecordVersionRefUpdate is the builder for updating RecordVersionRef entities.
type RecordVersionRefUpdate struct {
	config
	hooks    []Hook
	mutation *RecordVersionRefMutation
}

// Where appends a list predicates to the RecordVersionRefUpdate builder.
func (_u *RecordVersionRefUpdate) Where(ps ...predicate.RecordVersionRef) *RecordVersionRefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecordVersionRefUpdate) SetUpdatedAt(v string) *RecordVersionRefUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableUpdatedAt(v *string) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *RecordVersionRefUpdate) SetProjectID(v string) *RecordVersionRefUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableProjectID(v *string) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRecordVersionID sets the "record_version_id" field.
func (_u *RecordVersionRefUpdate) SetRecordVersionID(v string) *RecordVersionRefUpdate {
	_u.mutation.SetRecordVersionID(v)
	return _u
}

// SetNillableRecordVersionID sets the "record_version_id" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableRecordVersionID(v *string) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetRecordVersionID(*v)
	}
	return _u
}

// SetRelation sets the "relation" field.
func (_u *RecordVersionRefUpdate) SetRelation(v string) *RecordVersionRefUpdate {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableRelation(v *string) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetTargetSlug sets the "target_slug" field.
func (_u *RecordVersionRefUpdate) SetTargetSlug(v string) *RecordVersionRefUpdate {
	_u.mutation.SetTargetSlug(v)
	return _u
}

// SetNillableTargetSlug sets the "target_slug" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableTargetSlug(v *string) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetTargetSlug(*v)
	}
	return _u
}

// SetTargetOwningRoot sets the "target_owning_root" field.
func (_u *RecordVersionRefUpdate) SetTargetOwningRoot(v string) *RecordVersionRefUpdate {
	_u.mutation.SetTargetOwningRoot(v)
	return _u
}

// SetNillableTargetOwningRoot sets the "target_owning_root" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableTargetOwningRoot(v *string) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetTargetOwningRoot(*v)
	}
	return _u
}

// ClearTargetOwningRoot clears the value of the "target_owning_root" field.
func (_u *RecordVersionRefUpdate) ClearTargetOwningRoot() *RecordVersionRefUpdate {
	_u.mutation.ClearTargetOwningRoot()
	return _u
}

// SetDangling sets the "dangling" field.
func (_u *RecordVersionRefUpdate) SetDangling(v int8) *RecordVersionRefUpdate {
	_u.mutation.ResetDangling()
	_u.mutation.SetDangling(v)
	return _u
}

// SetNillableDangling sets the "dangling" field if the given value is not nil.
func (_u *RecordVersionRefUpdate) SetNillableDangling(v *int8) *RecordVersionRefUpdate {
	if v != nil {
		_u.SetDangling(*v)
	}
	return _u
}

// AddDangling adds value to the "dangling" field.
func (_u *RecordVersionRefUpdate) AddDangling(v int8) *RecordVersionRefUpdate {
	_u.mutation.AddDangling(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *RecordVersionRefUpdate) SetProject(v *Project) *RecordVersionRefUpdate {
	return _u.SetProjectID(v.ID)
}

// SetRecordVersion sets the "record_version" edge to the RecordVersion entity.
func (_u *RecordVersionRefUpdate) SetRecordVersion(v *RecordVersion) *RecordVersionRefUpdate {
	return _u.SetRecordVersionID(v.ID)
}

// Mutation returns the RecordVersionRefMutation object of the builder.
func (_u *RecordVersionRefUpdate) Mutation() *RecordVersionRefMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *RecordVersionRefUpdate) ClearProject() *RecordVersionRefUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearRecordVersion clears the "record_version" edge to the RecordVersion entity.
func (_u *RecordVersionRefUpdate) ClearRecordVersion() *RecordVersionRefUpdate {
	_u.mutation.ClearRecordVersion()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecordVersionRefUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecordVersionRefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecordVersionRefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecordVersionRefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecordVersionRefUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecordVersionRef.project"`)
	}
	if _u.mutation.RecordVersionCleared() && len(_u.mutation.RecordVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecordVersionRef.record_version"`)
	}
	return nil
}

func (_u *RecordVersionRefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recordversionref.Table, recordversionref.Columns, sqlgraph.NewFieldSpec(recordversionref.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recordversionref.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(recordversionref.FieldRelation, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetSlug(); ok {
		_spec.SetField(recordversionref.FieldTargetSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetOwningRoot(); ok {
		_spec.SetField(recordversionref.FieldTargetOwningRoot, field.TypeString, value)
	}
	if _u.mutation.TargetOwningRootCleared() {
		_spec.ClearField(recordversionref.FieldTargetOwningRoot, field.TypeString)
	}
	if value, ok := _u.mutation.Dangling(); ok {
		_spec.SetField(recordversionref.FieldDangling, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDangling(); ok {
		_spec.AddField(recordversionref.FieldDangling, field.TypeInt8, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.ProjectTable,
			Columns: []string{recordversionref.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.ProjectTable,
			Columns: []string{recordversionref.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordVersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.RecordVersionTable,
			Columns: []string{recordversionref.RecordVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.RecordVersionTable,
			Columns: []string{recordversionref.RecordVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recordversionref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecordVersionRefUpdateOne is the builder for updating a single RecordVersionRef entity.
type RecordVersionRefUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecordVersionRefMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecordVersionRefUpdateOne) SetUpdatedAt(v string) *RecordVersionRefUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableUpdatedAt(v *string) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *RecordVersionRefUpdateOne) SetProjectID(v string) *RecordVersionRefUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableProjectID(v *string) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRecordVersionID sets the "record_version_id" field.
func (_u *RecordVersionRefUpdateOne) SetRecordVersionID(v string) *RecordVersionRefUpdateOne {
	_u.mutation.SetRecordVersionID(v)
	return _u
}

// SetNillableRecordVersionID sets the "record_version_id" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableRecordVersionID(v *string) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetRecordVersionID(*v)
	}
	return _u
}

// SetRelation sets the "relation" field.
func (_u *RecordVersionRefUpdateOne) SetRelation(v string) *RecordVersionRefUpdateOne {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableRelation(v *string) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetTargetSlug sets the "target_slug" field.
func (_u *RecordVersionRefUpdateOne) SetTargetSlug(v string) *RecordVersionRefUpdateOne {
	_u.mutation.SetTargetSlug(v)
	return _u
}

// SetNillableTargetSlug sets the "target_slug" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableTargetSlug(v *string) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetTargetSlug(*v)
	}
	return _u
}

// SetTargetOwningRoot sets the "target_owning_root" field.
func (_u *RecordVersionRefUpdateOne) SetTargetOwningRoot(v string) *RecordVersionRefUpdateOne {
	_u.mutation.SetTargetOwningRoot(v)
	return _u
}

// SetNillableTargetOwningRoot sets the "target_owning_root" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableTargetOwningRoot(v *string) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetTargetOwningRoot(*v)
	}
	return _u
}

// ClearTargetOwningRoot clears the value of the "target_owning_root" field.
func (_u *RecordVersionRefUpdateOne) ClearTargetOwningRoot() *RecordVersionRefUpdateOne {
	_u.mutation.ClearTargetOwningRoot()
	return _u
}

// SetDangling sets the "dangling" field.
func (_u *RecordVersionRefUpdateOne) SetDangling(v int8) *RecordVersionRefUpdateOne {
	_u.mutation.ResetDangling()
	_u.mutation.SetDangling(v)
	return _u
}

// SetNillableDangling sets the "dangling" field if the given value is not nil.
func (_u *RecordVersionRefUpdateOne) SetNillableDangling(v *int8) *RecordVersionRefUpdateOne {
	if v != nil {
		_u.SetDangling(*v)
	}
	return _u
}

// AddDangling adds value to the "dangling" field.
func (_u *RecordVersionRefUpdateOne) AddDangling(v int8) *RecordVersionRefUpdateOne {
	_u.mutation.AddDangling(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *RecordVersionRefUpdateOne) SetProject(v *Project) *RecordVersionRefUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetRecordVersion sets the "record_version" edge to the RecordVersion entity.
func (_u *RecordVersionRefUpdateOne) SetRecordVersion(v *RecordVersion) *RecordVersionRefUpdateOne {
	return _u.SetRecordVersionID(v.ID)
}

// Mutation returns the RecordVersionRefMutation object of the builder.
func (_u *RecordVersionRefUpdateOne) Mutation() *RecordVersionRefMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *RecordVersionRefUpdateOne) ClearProject() *RecordVersionRefUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearRecordVersion clears the "record_version" edge to the RecordVersion entity.
func (_u *RecordVersionRefUpdateOne) ClearRecordVersion() *RecordVersionRefUpdateOne {
	_u.mutation.ClearRecordVersion()
	return _u
}

// Where appends a list predicates to the RecordVersionRefUpdate builder.
func (_u *RecordVersionRefUpdateOne) Where(ps ...predicate.RecordVersionRef) *RecordVersionRefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecordVersionRefUpdateOne) Select(field string, fields ...string) *RecordVersionRefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecordVersionRef entity.
func (_u *RecordVersionRefUpdateOne) Save(ctx context.Context) (*RecordVersionRef, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecordVersionRefUpdateOne) SaveX(ctx context.Context) *RecordVersionRef {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecordVersionRefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecordVersionRefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecordVersionRefUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecordVersionRef.project"`)
	}
	if _u.mutation.RecordVersionCleared() && len(_u.mutation.RecordVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecordVersionRef.record_version"`)
	}
	return nil
}

func (_u *RecordVersionRefUpdateOne) sqlSave(ctx context.Context) (_node *RecordVersionRef, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recordversionref.Table, recordversionref.Columns, sqlgraph.NewFieldSpec(recordversionref.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecordVersionRef.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recordversionref.FieldID)
		for _, f := range fields {
			if !recordversionref.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recordversionref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recordversionref.FieldUpdatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(recordversionref.FieldRelation, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetSlug(); ok {
		_spec.SetField(recordversionref.FieldTargetSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetOwningRoot(); ok {
		_spec.SetField(recordversionref.FieldTargetOwningRoot, field.TypeString, value)
	}
	if _u.mutation.TargetOwningRootCleared() {
		_spec.ClearField(recordversionref.FieldTargetOwningRoot, field.TypeString)
	}
	if value, ok := _u.mutation.Dangling(); ok {
		_spec.SetField(recordversionref.FieldDangling, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDangling(); ok {
		_spec.AddField(recordversionref.FieldDangling, field.TypeInt8, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.ProjectTable,
			Columns: []string{recordversionref.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.ProjectTable,
			Columns: []string{recordversionref.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordVersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.RecordVersionTable,
			Columns: []string{recordversionref.RecordVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recordversionref.RecordVersionTable,
			Columns: []string{recordversionref.RecordVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecordVersionRef{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recordversionref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
