// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/predicate"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/project"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversion"
	"github.com/franwerner/matecito-ai/apps/api/internal/store/ent/recordversionref"
)

// RecordVersionRefQuery is the builder for querying RecordVersionRef entities.
type RecordVersionRefQuery struct {
	config
	ctx               *QueryContext
	order             []recordversionref.OrderOption
	inters            []Interceptor
	predicates        []predicate.RecordVersionRef
	withProject       *ProjectQuery
	withRecordVersion *RecordVersionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecordVersionRefQuery builder.
func (_q *RecordVersionRefQuery) Where(ps ...predicate.RecordVersionRef) *RecordVersionRefQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RecordVersionRefQuery) Limit(limit int) *RecordVersionRefQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RecordVersionRefQuery) Offset(offset int) *RecordVersionRefQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RecordVersionRefQuery) Unique(unique bool) *RecordVersionRefQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RecordVersionRefQuery) Order(o ...recordversionref.OrderOption) *RecordVersionRefQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *RecordVersionRefQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversionref.Table, recordversionref.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversionref.ProjectTable, recordversionref.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRecordVersion chains the current query on the "record_version" edge.
func (_q *RecordVersionRefQuery) QueryRecordVersion() *RecordVersionQuery {
	query := (&RecordVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recordversionref.Table, recordversionref.FieldID, selector),
			sqlgraph.To(recordversion.Table, recordversion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordversionref.RecordVersionTable, recordversionref.RecordVersionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RecordVersionRef entity from the query.
// Returns a *NotFoundError when no RecordVersionRef was found.
func (_q *RecordVersionRefQuery) First(ctx context.Context) (*RecordVersionRef, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recordversionref.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RecordVersionRefQuery) FirstX(ctx context.Context) *RecordVersionRef {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecordVersionRef ID from the query.
// Returns a *NotFoundError when no RecordVersionRef ID was found.
func (_q *RecordVersionRefQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recordversionref.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RecordVersionRefQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecordVersionRef entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecordVersionRef entity is found.
// Returns a *NotFoundError when no RecordVersionRef entities are found.
func (_q *RecordVersionRefQuery) Only(ctx context.Context) (*RecordVersionRef, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recordversionref.Label}
	default:
		return nil, &NotSingularError{recordversionref.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RecordVersionRefQuery) OnlyX(ctx context.Context) *RecordVersionRef {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecordVersionRef ID in the query.
// Returns a *NotSingularError when more than one RecordVersionRef ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RecordVersionRefQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recordversionref.Label}
	default:
		err = &NotSingularError{recordversionref.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RecordVersionRefQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecordVersionRefs.
func (_q *RecordVersionRefQuery) All(ctx context.Context) ([]*RecordVersionRef, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RecordVersionRef, *RecordVersionRefQuery]()
	return withInterceptors[[]*RecordVersionRef](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RecordVersionRefQuery) AllX(ctx context.Context) []*RecordVersionRef {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecordVersionRef IDs.
func (_q *RecordVersionRefQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(recordversionref.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RecordVersionRefQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RecordVersionRefQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RecordVersionRefQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RecordVersionRefQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RecordVersionRefQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RecordVersionRefQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecordVersionRefQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RecordVersionRefQuery) Clone() *RecordVersionRefQuery {
	if _q == nil {
		return nil
	}
	return &RecordVersionRefQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]recordversionref.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.RecordVersionRef{}, _q.predicates...),
		withProject:       _q.withProject.Clone(),
		withRecordVersion: _q.withRecordVersion.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecordVersionRefQuery) WithProject(opts ...func(*ProjectQuery)) *RecordVersionRefQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithRecordVersion tells the query-builder to eager-load the nodes that are connected to
// the "record_version" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecordVersionRefQuery) WithRecordVersion(opts ...func(*RecordVersionQuery)) *RecordVersionRefQuery {
	query := (&RecordVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecordVersion = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecordVersionRef.Query().
//		GroupBy(recordversionref.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RecordVersionRefQuery) GroupBy(field string, fields ...string) *RecordVersionRefGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RecordVersionRefGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = recordversionref.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//	}
//
//	client.RecordVersionRef.Query().
//		Select(recordversionref.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RecordVersionRefQuery) Select(fields ...string) *RecordVersionRefSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RecordVersionRefSelect{RecordVersionRefQuery: _q}
	sbuild.label = recordversionref.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RecordVersionRefSelect configured with the given aggregations.
func (_q *RecordVersionRefQuery) Aggregate(fns ...AggregateFunc) *RecordVersionRefSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RecordVersionRefQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !recordversionref.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RecordVersionRefQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecordVersionRef, error) {
	var (
		nodes       = []*RecordVersionRef{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProject != nil,
			_q.withRecordVersion != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecordVersionRef).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecordVersionRef{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *RecordVersionRef, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRecordVersion; query != nil {
		if err := _q.loadRecordVersion(ctx, query, nodes, nil,
			func(n *RecordVersionRef, e *RecordVersion) { n.Edges.RecordVersion = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RecordVersionRefQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*RecordVersionRef, init func(*RecordVersionRef), assign func(*RecordVersionRef, *Project)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RecordVersionRef)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RecordVersionRefQuery) loadRecordVersion(ctx context.Context, query *RecordVersionQuery, nodes []*RecordVersionRef, init func(*RecordVersionRef), assign func(*RecordVersionRef, *RecordVersion)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RecordVersionRef)
	for i := range nodes {
		fk := nodes[i].RecordVersionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(recordversion.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "record_version_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RecordVersionRefQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RecordVersionRefQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(recordversionref.Table, recordversionref.Columns, sqlgraph.NewFieldSpec(recordversionref.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recordversionref.FieldID)
		for i := range fields {
			if fields[i] != recordversionref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(recordversionref.FieldProjectID)
		}
		if _q.withRecordVersion != nil {
			_spec.Node.AddColumnOnce(recordversionref.FieldRecordVersionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RecordVersionRefQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(recordversionref.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = recordversionref.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecordVersionRefGroupBy is the group-by builder for RecordVersionRef entities.
type RecordVersionRefGroupBy struct {
	selector
	build *RecordVersionRefQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RecordVersionRefGroupBy) Aggregate(fns ...AggregateFunc) *RecordVersionRefGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RecordVersionRefGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecordVersionRefQuery, *RecordVersionRefGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RecordVersionRefGroupBy) sqlScan(ctx context.Context, root *RecordVersionRefQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RecordVersionRefSelect is the builder for selecting fields of RecordVersionRef entities.
type RecordVersionRefSelect struct {
	*RecordVersionRefQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RecordVersionRefSelect) Aggregate(fns ...AggregateFunc) *RecordVersionRefSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RecordVersionRefSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecordVersionRefQuery, *RecordVersionRefSelect](ctx, _s.RecordVersionRefQuery, _s, _s.inters, v)
}

func (_s *RecordVersionRefSelect) sqlScan(ctx context.Context, root *RecordVersionRefQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
